# Generated by Django 6.0.4 on 2026-04-28 15:27

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, default='default/default.png', null=True, upload_to='Products/CustomProducts/')),
                ('barcode', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('jewelry_type', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('retail_lower_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('retail_top_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('wholesale_lower_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('wholesale_top_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('height', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.CharField(blank=True, max_length=255, null=True)),
                ('price_currency', models.CharField(choices=[('HS', 'Has Altın'), ('HG', 'Has Gümüş'), ('TRY', 'Türk Lirası'), ('USD', 'Amerikan Doları'), ('EUR', 'Euro'), ('GBP', 'İngiliz Sterlini'), ('CAD', 'Kanada Doları'), ('QAR', 'Katar Riyali'), ('CHF', 'İsviçre Frangı'), ('JPY', 'Japon Yeni'), ('SAR', 'Suudi Arabistan Riyali'), ('AED', 'BAE Dirhemi'), ('AUD', 'Avustralya Doları'), ('KWD', 'Kuveyt Dinarı'), ('OMR', 'Umman Riyali'), ('RUB', 'Rus Rublesi'), ('BGN', 'Bulgar Levası'), ('NOK', 'Norveç Kronu'), ('SEK', 'İsveç Kronu'), ('DKK', 'Danimarka Kronu'), ('CNY', 'Çin Yuanı'), ('ILS', 'Yeni İsrail Şekeli'), ('MAD', 'Fas Dirhemi'), ('JOD', 'Ürdün Dinarı')], default='HS', max_length=10)),
                ('fixed_labor_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Sabit İşçilik Tutarı (Birim)')),
                ('material_type', models.CharField(choices=[('GOLD', 'Altın'), ('SILVER', 'Gümüş'), ('WATCH', 'Saat'), ('DIAMOND', 'Pırlanta')], db_index=True, default='GOLD', help_text='Ürünün fiziksel kategorisi. Mevcut tüm altın kayıtları otomatik olarak GOLD değerine düşer. Saat ve Pırlanta için WatchDetail/DiamondDetail uzantı tablolarına veri girilir.', max_length=10, verbose_name='Materyal Tipi')),
                ('workmanship_type', models.BooleanField(blank=True, default=True, null=True)),
                ('gold_dry', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.000000'), max_digits=10, null=True)),
                ('gold_rate', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.000000'), max_digits=10, null=True)),
                ('product_mileage', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=10, null=True)),
                ('labor_mileage', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=10, null=True)),
                ('piece_labor', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('rfid_code', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='RFID Kodu')),
                ('ring_size', models.CharField(blank=True, max_length=10, null=True, verbose_name='Alyans Numarası')),
                ('sale_price_hs', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=10, null=True)),
                ('sale_price_tl', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('product_hs', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=10, null=True)),
                ('buy_price_hs', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=10, null=True)),
                ('buy_price_tl', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('gram', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=10, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('certificate', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('is_scrap', models.BooleanField(blank=True, default=False, null=True)),
                ('is_gram_bullion', models.BooleanField(blank=True, default=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('is_protected', models.BooleanField(blank=True, default=False, null=True)),
                ('is_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('is_currency', models.BooleanField(default=False, help_text='True ise bu ürün bir para birimi temsilidir (TRY, USD, EUR vb.). Stok Yönetimi listesinde gösterilmez ve nakit işlemlerinde update_product_stock() çağrılmaz.', verbose_name='Para Birimi Ürünü')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.categories')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.stores')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='DiamondDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mount_metal', models.CharField(blank=True, choices=[('GOLD_YELLOW', 'Sarı Altın'), ('GOLD_WHITE', 'Beyaz Altın'), ('GOLD_ROSE', 'Rose (Pembe) Altın'), ('PLATINUM', 'Platin'), ('SILVER', 'Gümüş'), ('OTHER', 'Diğer')], default='GOLD_YELLOW', help_text='Pırlantanın oturduğu metal (sarı/beyaz altın, platin, vb.).', max_length=20, null=True, verbose_name='Montür Metali')),
                ('mount_karat', models.CharField(blank=True, choices=[('8K', '8 Ayar (333)'), ('14K', '14 Ayar (585)'), ('18K', '18 Ayar (750)'), ('22K', '22 Ayar (916)'), ('24K', '24 Ayar (Has)'), ('NONE', 'Montürsüz / Yok')], default='18K', help_text='Örn: 18K. Has hesabına EKLENMEZ; yalnızca etiket/sigorta amaçlı.', max_length=5, null=True, verbose_name='Montür Ayarı')),
                ('mount_gram', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), help_text='Örn: 4.100 gr. Has hesabına EKLENMEZ.', max_digits=8, null=True, verbose_name='Montür Gramı')),
                ('sale_currency', models.CharField(blank=True, choices=[('USD', 'Amerikan Doları'), ('EUR', 'Euro'), ('GBP', 'İngiliz Sterlini'), ('TRY', 'Türk Lirası')], default='USD', help_text='Satış ekranı bu birim × günlük kur ile TL fiyatı hesaplar.', max_length=5, null=True, verbose_name='Satış Döviz Cinsi')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='sale_currency biriminde ürünün satış fiyatı.', max_digits=14, null=True, verbose_name='Satış Fiyatı (Döviz Cinsinde)')),
                ('carat_weight', models.DecimalField(blank=True, decimal_places=4, help_text='Tekil taşlı ürünlerde bu alan kullanılır. Çoklu taşta stones toplamı geçerlidir.', max_digits=8, null=True, verbose_name='Karat Ağırlığı (Toplam/Summary)')),
                ('shape', models.CharField(blank=True, choices=[('ROUND', 'Yuvarlak (Round)'), ('PRINCESS', 'Prenses (Princess)'), ('OVAL', 'Oval'), ('MARQUISE', 'Markiz (Marquise)'), ('PEAR', 'Damla (Pear)'), ('CUSHION', 'Yastık (Cushion)'), ('EMERALD', 'Zümrüt (Emerald)'), ('ASSCHER', 'Asscher'), ('RADIANT', 'Radiant'), ('HEART', 'Kalp (Heart)'), ('BAGUETTE', 'Baget'), ('OTHER', 'Diğer')], max_length=20, null=True, verbose_name='Kesim Şekli (Summary)')),
                ('color_grade', models.CharField(blank=True, choices=[('D', 'D (Renksiz)'), ('E', 'E (Renksiz)'), ('F', 'F (Renksiz)'), ('G', 'G (Neredeyse Renksiz)'), ('H', 'H (Neredeyse Renksiz)'), ('I', 'I (Neredeyse Renksiz)'), ('J', 'J (Neredeyse Renksiz)'), ('K', 'K (Hafif Sarı)'), ('L', 'L (Hafif Sarı)'), ('M', 'M (Hafif Sarı)'), ('N', 'N+ (Sarımsı)')], max_length=2, null=True, verbose_name='Renk Derecesi (Summary)')),
                ('clarity_grade', models.CharField(blank=True, choices=[('FL', 'FL (Kusursuz)'), ('IF', 'IF (İç Kusursuz)'), ('VVS1', 'VVS1'), ('VVS2', 'VVS2'), ('VS1', 'VS1'), ('VS2', 'VS2'), ('SI1', 'SI1'), ('SI2', 'SI2'), ('I1', 'I1'), ('I2', 'I2'), ('I3', 'I3')], max_length=4, null=True, verbose_name='Berraklık Derecesi (Summary)')),
                ('cut_grade', models.CharField(blank=True, choices=[('EXCELLENT', 'Mükemmel'), ('VERY_GOOD', 'Çok İyi'), ('GOOD', 'İyi'), ('FAIR', 'Orta'), ('POOR', 'Zayıf')], max_length=12, null=True, verbose_name='Kesim Kalitesi (Summary)')),
                ('certificate_lab', models.CharField(blank=True, choices=[('GIA', 'GIA (Gemological Institute of America)'), ('IGI', 'IGI (International Gemological Institute)'), ('HRD', 'HRD Antwerp'), ('AGS', 'AGS (American Gem Society)'), ('GSI', 'GSI (Gemological Science International)'), ('NONE', 'Sertifikasız'), ('OTHER', 'Diğer')], default='NONE', max_length=10, null=True, verbose_name='Sertifika Laboratuvarı (Piece-Level)')),
                ('certificate_no', models.CharField(blank=True, help_text="Ürün bütünü için verilmiş sertifika. Taş bazlı sertifika DiamondStone'dadır.", max_length=64, null=True, verbose_name='Sertifika Numarası (Piece-Level)')),
                ('supplier_ref', models.CharField(blank=True, help_text='Üretici/tedarikçi tarafından parçaya atanmış referans kodu (örn: RAI5.61-27).', max_length=64, null=True, verbose_name='Üretici Referans Kodu')),
                ('fluorescence', models.CharField(blank=True, choices=[('NONE', 'Yok'), ('FAINT', 'Hafif'), ('MEDIUM', 'Orta'), ('STRONG', 'Güçlü'), ('VSTRONG', 'Çok Güçlü')], max_length=10, null=True, verbose_name='Floresans')),
                ('depth_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Taşın derinlik oranı, yüzde olarak.', max_digits=5, null=True, verbose_name='Derinlik (%)')),
                ('table_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Taşın tabla genişliği oranı, yüzde olarak.', max_digits=5, null=True, verbose_name='Tabla (%)')),
                ('is_mounted', models.BooleanField(default=True, help_text='Varsayılan True — mount_karat/mount_gram doluysa monte sayılır.', verbose_name='Monte Edilmiş Mi?')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('product', models.OneToOneField(help_text="Bu detayların ait olduğu Products kaydı (material_type='DIAMOND').", on_delete=django.db.models.deletion.CASCADE, related_name='diamond_detail', to='products.products', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Pırlanta Detayı',
                'verbose_name_plural': 'Pırlanta Detayları',
                'db_table': 'DiamondDetail',
            },
        ),
        migrations.CreateModel(
            name='WatchDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, db_index=True, help_text='Örn: Rolex, Omega, Patek Philippe, Audemars Piguet.', max_length=100, null=True, verbose_name='Marka')),
                ('model_name', models.CharField(blank=True, help_text='Örn: Submariner, Seamaster, Nautilus, Royal Oak.', max_length=150, null=True, verbose_name='Model Adı')),
                ('reference_no', models.CharField(blank=True, db_index=True, help_text='Üreticinin model referans kodu. Örn: Rolex 126610LN.', max_length=64, null=True, verbose_name='Üretici Referans No')),
                ('serial_no', models.CharField(blank=True, help_text='Saatin tekil üretim seri numarası.', max_length=64, null=True, unique=True, verbose_name='Seri Numarası')),
                ('movement_type', models.CharField(blank=True, choices=[('AUTOMATIC', 'Otomatik'), ('MANUAL', 'Manuel (Kurmalı)'), ('QUARTZ', 'Quartz (Pilli)'), ('SMART', 'Akıllı (Smart)'), ('HYBRID', 'Hibrit')], max_length=15, null=True, verbose_name='Mekanizma Tipi')),
                ('case_material', models.CharField(blank=True, choices=[('STEEL', 'Çelik'), ('GOLD_YELLOW', 'Sarı Altın'), ('GOLD_WHITE', 'Beyaz Altın'), ('GOLD_ROSE', 'Rose (Pembe) Altın'), ('PLATINUM', 'Platin'), ('TITANIUM', 'Titanyum'), ('CERAMIC', 'Seramik'), ('BRONZE', 'Bronz'), ('OTHER', 'Diğer')], max_length=15, null=True, verbose_name='Kasa Malzemesi')),
                ('case_diameter', models.DecimalField(blank=True, decimal_places=1, help_text='Kasa genişliği mm cinsinden. Örn: 40.0, 41.5.', max_digits=5, null=True, verbose_name='Kasa Çapı (mm)')),
                ('year_of_mfg', models.PositiveSmallIntegerField(blank=True, help_text='Saatin üretildiği yıl (4 haneli).', null=True, verbose_name='Üretim Yılı')),
                ('warranty_date', models.DateField(blank=True, null=True, verbose_name='Garanti Bitiş Tarihi')),
                ('box_papers', models.BooleanField(default=False, help_text='Saatin orijinal kutusu ve/veya garanti belgesi mevcut mu? İkinci el fiyatlamada kritik bir faktördür.', verbose_name='Box & Papers')),
                ('condition', models.CharField(choices=[('NEW', 'Sıfır / Yeni'), ('LIKE_NEW', 'Sıfır Ayarında'), ('GOOD', 'İyi Durumda'), ('FAIR', 'Orta Durumda'), ('VINTAGE', 'Vintage / Antika'), ('FOR_PARTS', 'Parça İçin')], default='NEW', max_length=15, verbose_name='Durum')),
                ('sale_currency', models.CharField(blank=True, choices=[('USD', 'Amerikan Doları'), ('EUR', 'Euro'), ('GBP', 'İngiliz Sterlini'), ('CHF', 'İsviçre Frangı'), ('TRY', 'Türk Lirası')], default='USD', help_text='Satış ekranı bu birim × günlük kur ile TL fiyatı hesaplar.', max_length=5, null=True, verbose_name='Satış Döviz Cinsi')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='sale_currency biriminde saatin satış fiyatı.', max_digits=14, null=True, verbose_name='Satış Fiyatı (Döviz Cinsinde)')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
                ('product', models.OneToOneField(help_text="Bu detayların ait olduğu Products kaydı (material_type='WATCH').", on_delete=django.db.models.deletion.CASCADE, related_name='watch_detail', to='products.products', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Saat Detayı',
                'verbose_name_plural': 'Saat Detayları',
                'db_table': 'WatchDetail',
            },
        ),
        migrations.CreateModel(
            name='DiamondStone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stone_type', models.CharField(choices=[('DIAMOND', 'Pırlanta'), ('EMERALD', 'Zümrüt'), ('RUBY', 'Yakut'), ('SAPPHIRE', 'Safir'), ('PEARL', 'İnci'), ('ALEXANDRITE', 'İskenderit'), ('OTHER', 'Diğer')], default='DIAMOND', help_text='Pırlanta veya renkli taş türü. Renkli taşlarda GIA renk skalası yerine serbest renk metni kullanılır.', max_length=16, verbose_name='Taş Türü')),
                ('role', models.CharField(choices=[('CENTER', 'Merkez Taş (D1)'), ('SIDE', 'Yan Taş (D2+)'), ('ACCENT', 'Aksesuar Taş')], default='CENTER', help_text='CENTER = Merkez taş (D1). SIDE = Yan taşlar (D2+). ACCENT = aksesuar.', max_length=10, verbose_name='Taş Rolü')),
                ('position', models.PositiveSmallIntegerField(default=1, help_text='D1 için 1, D2 için 2, ... Etikette görünen sıra.', verbose_name='Sıra No')),
                ('carat_weight', models.DecimalField(decimal_places=4, help_text='Bu taşa özel karat. Örn: 0.26.', max_digits=8, verbose_name='Karat Ağırlığı')),
                ('shape', models.CharField(blank=True, choices=[('ROUND', 'Yuvarlak (Round)'), ('PRINCESS', 'Prenses (Princess)'), ('OVAL', 'Oval'), ('MARQUISE', 'Markiz (Marquise)'), ('PEAR', 'Damla (Pear)'), ('CUSHION', 'Yastık (Cushion)'), ('EMERALD', 'Zümrüt (Emerald)'), ('ASSCHER', 'Asscher'), ('RADIANT', 'Radiant'), ('HEART', 'Kalp (Heart)'), ('BAGUETTE', 'Baget'), ('OTHER', 'Diğer')], default='ROUND', max_length=20, null=True, verbose_name='Kesim Şekli')),
                ('color_grade', models.CharField(blank=True, help_text='Pırlanta için GIA skalası (D-N). Renkli taşlar için serbest metin (örn: Yeşil, Kırmızı).', max_length=24, null=True, verbose_name='Renk')),
                ('clarity_grade', models.CharField(blank=True, choices=[('FL', 'FL (Kusursuz)'), ('IF', 'IF (İç Kusursuz)'), ('VVS1', 'VVS1'), ('VVS2', 'VVS2'), ('VS1', 'VS1'), ('VS2', 'VS2'), ('SI1', 'SI1'), ('SI2', 'SI2'), ('I1', 'I1'), ('I2', 'I2'), ('I3', 'I3')], max_length=4, null=True, verbose_name='Berraklık')),
                ('cut_grade', models.CharField(blank=True, choices=[('EXCELLENT', 'Mükemmel'), ('VERY_GOOD', 'Çok İyi'), ('GOOD', 'İyi'), ('FAIR', 'Orta'), ('POOR', 'Zayıf')], max_length=12, null=True, verbose_name='Kesim')),
                ('certificate_lab', models.CharField(blank=True, choices=[('GIA', 'GIA (Gemological Institute of America)'), ('IGI', 'IGI (International Gemological Institute)'), ('HRD', 'HRD Antwerp'), ('AGS', 'AGS (American Gem Society)'), ('GSI', 'GSI (Gemological Science International)'), ('NONE', 'Sertifikasız'), ('OTHER', 'Diğer')], default='NONE', max_length=10, null=True, verbose_name='Sertifika Laboratuvarı')),
                ('certificate_no', models.CharField(blank=True, help_text='Merkez taşlar genellikle GIA/IGI sertifikasıyla gelir. Yan taşlar sertifikasız olabilir (null).', max_length=64, null=True, unique=True, verbose_name='Sertifika No (Bu Taş İçin)')),
                ('fluorescence', models.CharField(blank=True, choices=[('NONE', 'Yok'), ('FAINT', 'Hafif'), ('MEDIUM', 'Orta'), ('STRONG', 'Güçlü'), ('VSTRONG', 'Çok Güçlü')], max_length=10, null=True, verbose_name='Floresans')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Taş Notu')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('diamond_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stones', to='products.diamonddetail', verbose_name='Pırlanta Ürünü Detayı')),
            ],
            options={
                'verbose_name': 'Pırlanta Taşı',
                'verbose_name_plural': 'Pırlanta Taşları',
                'db_table': 'DiamondStone',
                'ordering': ['diamond_detail', 'position'],
                'indexes': [models.Index(fields=['diamond_detail'], name='diastone_detail_idx'), models.Index(fields=['color_grade', 'clarity_grade'], name='diastone_color_clarity_idx'), models.Index(fields=['certificate_no'], name='diastone_cert_idx')],
                'constraints': [models.UniqueConstraint(fields=('diamond_detail', 'position'), name='diastone_unique_detail_position')],
            },
        ),
        migrations.AddIndex(
            model_name='diamonddetail',
            index=models.Index(fields=['certificate_no'], name='diadet_cert_no_idx'),
        ),
        migrations.AddIndex(
            model_name='diamonddetail',
            index=models.Index(fields=['shape', 'color_grade', 'clarity_grade'], name='diadet_4c_idx'),
        ),
        migrations.AddIndex(
            model_name='diamonddetail',
            index=models.Index(fields=['sale_currency'], name='diadet_salecur_idx'),
        ),
        migrations.AddIndex(
            model_name='diamonddetail',
            index=models.Index(fields=['mount_karat'], name='diadet_mountk_idx'),
        ),
        migrations.AddIndex(
            model_name='watchdetail',
            index=models.Index(fields=['brand', 'model_name'], name='watchdet_brand_model_idx'),
        ),
        migrations.AddIndex(
            model_name='watchdetail',
            index=models.Index(fields=['reference_no'], name='watchdet_ref_no_idx'),
        ),
        migrations.AddIndex(
            model_name='watchdetail',
            index=models.Index(fields=['serial_no'], name='watchdet_serial_no_idx'),
        ),
        migrations.AddIndex(
            model_name='watchdetail',
            index=models.Index(fields=['sale_currency'], name='watchdet_salecur_idx'),
        ),
    ]
