# Generated by Django 6.0.5 on 2026-07-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diamonddetail',
            name='growth_type',
            field=models.CharField(blank=True, choices=[('NATURAL', 'Doğal (Natural)'), ('LAB_GROWN', 'Laboratuvar (Lab-Grown)')], help_text='Doğal mı laboratuvar üretimi mi (etikette NAT/LAB). Boş = bilinmiyor; eski kayıtlarda boş bırakılır, NATURAL varsayılmaz.', max_length=10, null=True, verbose_name='Taş Kökeni'),
        ),
    ]
