# Generated by Django 6.0.4 on 2026-05-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('company_name', models.CharField(max_length=100, verbose_name='Kuyumcu/Firma Adı')),
                ('logo', models.ImageField(upload_to='testimonials/', verbose_name='Firma Logosu')),
                ('message', models.TextField(max_length=300, verbose_name='Müşteri Yorumu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayında mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Referans / Müşteri Yorumu',
                'verbose_name_plural': 'Referanslar',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
