# Generated by Django 6.0.4 on 2026-04-28 15:27

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStoreReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateField(db_index=True, verbose_name='Rapor Tarihi')),
                ('total_sales_tl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Toplam Satış (TL)')),
                ('total_sales_hs', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Toplam Satış (Has)')),
                ('sale_count', models.IntegerField(default=0, verbose_name='Satış Adet')),
                ('unique_customers', models.IntegerField(default=0, verbose_name='Tekil Müşteri Sayısı')),
                ('total_purchases_tl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Toplam Alış (TL)')),
                ('total_purchases_hs', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Toplam Alış (Has)')),
                ('purchase_count', models.IntegerField(default=0, verbose_name='Alış Adet')),
                ('total_returns_tl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Toplam İade (TL)')),
                ('return_count', models.IntegerField(default=0, verbose_name='İade Adet')),
                ('total_gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Toplam Brüt Kâr (TL)')),
                ('total_net_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Toplam Net Kâr (TL)')),
                ('cash_in', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Nakit Giriş (TL)')),
                ('cash_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Nakit Çıkış (TL)')),
                ('card_in', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Kredi Kartı Giriş (TL)')),
                ('card_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Kredi Kartı Çıkış (TL)')),
                ('transfer_in', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Havale Giriş (TL)')),
                ('transfer_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Havale Çıkış (TL)')),
                ('commission_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Toplam Komisyon (TL)')),
                ('transaction_count', models.IntegerField(default=0, verbose_name='Toplam İşlem Sayısı')),
                ('stock_value_tl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gün sonunda StockSnapshot WAC bazlı toplam stok değeri.', max_digits=18, verbose_name='Stok Değeri (WAC TL)')),
                ('stock_value_hs', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Stok Değeri (WAC Has)')),
                ('silver_stock_gram', models.DecimalField(blank=True, decimal_places=4, default=None, help_text='Material_type=SILVER ürünlerin toplam gramı.', max_digits=14, null=True, verbose_name='Gümüş Stok (Gram)')),
                ('silver_stock_value_hg', models.DecimalField(blank=True, decimal_places=4, default=None, help_text='Material_type=SILVER WAC Has Gümüş cinsinden toplam değer.', max_digits=14, null=True, verbose_name='Gümüş Stok Değeri (Has Gümüş)')),
                ('silver_stock_value_tl', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Material_type=SILVER WAC TL cinsinden toplam değer.', max_digits=18, null=True, verbose_name='Gümüş Stok Değeri (TL)')),
                ('diamond_stock_pieces', models.IntegerField(blank=True, default=None, help_text='Material_type=DIAMOND ürünlerin toplam adedi.', null=True, verbose_name='Pırlanta Stok (Adet)')),
                ('diamond_stock_value_tl', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Material_type=DIAMOND WAC TL cinsinden toplam değer.', max_digits=18, null=True, verbose_name='Pırlanta Stok Değeri (TL)')),
                ('watch_stock_pieces', models.IntegerField(blank=True, default=None, help_text='Material_type=WATCH ürünlerin toplam adedi.', null=True, verbose_name='Saat Stok (Adet)')),
                ('watch_stock_value_tl', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Material_type=WATCH WAC TL cinsinden toplam değer.', max_digits=18, null=True, verbose_name='Saat Stok Değeri (TL)')),
                ('computed_at', models.DateTimeField(help_text='Son hesaplama zamanı. Delta güncellemeler bu alanı günceller.', verbose_name='Hesaplandığı Zaman')),
            ],
            options={
                'verbose_name': 'Günlük Mağaza Raporu',
                'verbose_name_plural': 'Günlük Mağaza Raporları',
                'db_table': 'DailyStoreReport',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True, verbose_name='Celery Task ID')),
                ('report_type', models.CharField(max_length=64, verbose_name='Rapor Tipi')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='PDF Dosyası')),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('SUCCESS', 'Tamamlandı'), ('FAILED', 'Hata')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Hata Mesajı')),
            ],
            options={
                'verbose_name': 'Üretilen Rapor',
                'verbose_name_plural': 'Üretilen Raporlar',
                'db_table': 'GeneratedReports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyEmployeeReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateField(db_index=True)),
                ('sale_count', models.IntegerField(default=0)),
                ('total_sales_tl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_sales_hs', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('total_gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('purchase_count', models.IntegerField(default=0)),
                ('total_purchases_tl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('transaction_count', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Personel Günlük Raporu',
                'verbose_name_plural': 'Personel Günlük Raporları',
                'db_table': 'DailyEmployeeReport',
                'ordering': ['-report_date'],
            },
        ),
    ]
