# Generated by Django 6.0.4 on 2026-05-09 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyemployeereport',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_employee_reports', to='stores.stores'),
        ),
        migrations.AddField(
            model_name='dailystorereport',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='stores.stores', verbose_name='Mağaza'),
        ),
        migrations.AddIndex(
            model_name='generatedreports',
            index=models.Index(fields=['task_id'], name='genrep_task_id_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreports',
            index=models.Index(fields=['status'], name='genrep_status_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreports',
            index=models.Index(fields=['-created_at'], name='genrep_created_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyemployeereport',
            index=models.Index(fields=['store', 'report_date'], name='daily_emp_store_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyemployeereport',
            index=models.Index(fields=['employee', 'report_date'], name='daily_emp_emp_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyemployeereport',
            constraint=models.UniqueConstraint(fields=('store', 'employee', 'report_date'), name='daily_emp_unique_store_emp_date'),
        ),
        migrations.AddIndex(
            model_name='dailystorereport',
            index=models.Index(fields=['store', 'report_date'], name='dailyrep_store_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystorereport',
            index=models.Index(fields=['report_date'], name='dailyrep_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystorereport',
            index=models.Index(fields=['-computed_at'], name='dailyrep_computed_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailystorereport',
            constraint=models.UniqueConstraint(fields=('store', 'report_date'), name='dailyreport_unique_store_date'),
        ),
    ]
