# Generated by Django 6.0.4 on 2026-04-28 15:27

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('WA_CREDIT', 'WhatsApp Kontör'), ('EINVOICE_CREDIT', 'E-Fatura Kontör'), ('PACKAGE', 'Paket Satın Alma'), ('PROPOSAL', 'Teklif Onayı')], max_length=24)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_label', models.CharField(default='adet', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('currency', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR'), ('HS', 'HS')], default='TRY', max_length=8)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'OrderItems',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_no', models.CharField(db_index=True, max_length=40, unique=True)),
                ('sequence_no', models.PositiveIntegerField(default=0)),
                ('order_type', models.CharField(choices=[('WA_CREDIT', 'WhatsApp Kontör'), ('EINVOICE_CREDIT', 'E-Fatura Kontör'), ('PACKAGE', 'Paket Satın Alma'), ('PROPOSAL', 'Teklif Onayı')], max_length=24)),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('PENDING', 'Beklemede'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi'), ('CANCELED', 'İptal'), ('FULFILLED', 'Tamamlandı')], default='PENDING', max_length=16)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Ödenmedi'), ('PARTIAL', 'Kısmi'), ('PAID', 'Ödendi'), ('REFUNDED', 'İade Edildi')], default='UNPAID', max_length=16)),
                ('currency', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR'), ('HS', 'HS')], default='TRY', max_length=8)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('paid_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_approved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
