# Generated by Django 6.0.4 on 2026-04-28 15:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveBoardSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_board_name', models.CharField(blank=True, default='', help_text='Boş bırakılırsa mağaza adı gösterilir.', max_length=255, verbose_name='Özel Ekran Adı')),
                ('custom_board_logo', models.ImageField(blank=True, help_text='Boş bırakılırsa mağaza logosu gösterilir.', null=True, upload_to='LiveBoard/logos/', verbose_name='Özel Ekran Logosu')),
                ('show_custom_name', models.BooleanField(default=True, verbose_name='Özel Mağaza Adı Göster')),
                ('show_custom_logo', models.BooleanField(default=True, verbose_name='Özel Logo Göster')),
                ('show_currency_section', models.BooleanField(default=True, verbose_name='Döviz Bölümü Aktif')),
                ('show_sarrafiye_section', models.BooleanField(default=True, verbose_name='Sarrafiye Bölümü Aktif')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Canlı Ekran Ayarı',
                'verbose_name_plural': 'Canlı Ekran Ayarları',
                'db_table': 'LiveBoardSettings',
            },
        ),
    ]
