# Generated by Django 6.0.4 on 2026-04-28 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('live_board', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveboardsettings',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_board_settings', to='stores.stores', verbose_name='Mağaza'),
        ),
    ]
