# Generated by Django 6.0.5 on 2026-05-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_board', '0003_kitcopricecache'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveboardsettings',
            name='kitco_display_currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP'), ('CHF', 'CHF'), ('CAD', 'CAD'), ('AUD', 'AUD'), ('JPY', 'JPY')], default='EUR', help_text="Kitco spot fiyatlarının live board'da gösterildiği para birimi.", max_length=8, verbose_name='Kitco Gösterim Para Birimi'),
        ),
        migrations.AddField(
            model_name='liveboardsettings',
            name='kitco_display_unit',
            field=models.CharField(choices=[('GRAM', 'Gram'), ('OZ', 'Troy Ons')], default='GRAM', help_text="Kitco spot fiyatlarının live board'da gösterildiği birim.", max_length=8, verbose_name='Kitco Gösterim Birimi'),
        ),
        migrations.AddField(
            model_name='liveboardsettings',
            name='show_kitco_section',
            field=models.BooleanField(default=True, help_text='Kitco uluslararası değerli metal spot fiyat panelini (Altın, Gümüş, Platin, Paladyum, Rodyum) gösterir/gizler.', verbose_name='Kitco Spot Fiyat Panelini Göster'),
        ),
    ]
