# Generated by Django 6.0.5 on 2026-05-11 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_board', '0004_liveboardsettings_kitco_display_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveboardsettings',
            name='hidden_items',
        ),
        migrations.RemoveField(
            model_name='liveboardsettings',
            name='live_board_item_order',
        ),
        migrations.RemoveField(
            model_name='liveboardsettings',
            name='show_currency_section',
        ),
        migrations.RemoveField(
            model_name='liveboardsettings',
            name='show_sarrafiye_section',
        ),
    ]
