# Generated by Django 6.0.4 on 2026-04-28 15:27

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('process_no', models.CharField(blank=True, default='', max_length=100)),
                ('transaction_type', models.CharField(choices=[('DEBT', 'Borç (müşteri mağazaya borçlandı)'), ('CREDIT', 'Alacak (mağaza müşteriye borçlandı)')], max_length=10)),
                ('amount_hs', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('exchange_rate_tl', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=18)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'CustomerLedger',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('identification_number', models.CharField(blank=True, max_length=11, null=True)),
                ('customer_number', models.CharField(blank=True, max_length=25, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('tax_office_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Vergi Dairesi Kodu')),
                ('address', models.TextField(blank=True, null=True)),
                ('identification_front_image', models.ImageField(blank=True, null=True, upload_to='customers/identity/')),
                ('identification_back_image', models.ImageField(blank=True, null=True, upload_to='customers/identity/')),
                ('receivable_hs', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('payable_hs', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('is_email_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('is_phone_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'Customers',
            },
        ),
    ]
