# Generated by Django 6.0.4 on 2026-05-09 16:01

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custody', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('identification_number', models.CharField(blank=True, max_length=11, null=True)),
                ('customer_number', models.CharField(blank=True, max_length=25, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('tax_office_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Vergi Dairesi Kodu')),
                ('address', models.TextField(blank=True, null=True)),
                ('identification_front_image', models.ImageField(blank=True, null=True, upload_to='customers/identity/')),
                ('identification_back_image', models.ImageField(blank=True, null=True, upload_to='customers/identity/')),
                ('receivable_hs', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('payable_hs', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('is_email_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('is_phone_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('DEBT', 'Borç (müşteri mağazaya borçlandı)'), ('CREDIT', 'Alacak (mağaza müşteriye borçlandı)'), ('COLLECTION_TL', 'TL Nakit Tahsilat'), ('COLLECTION_FX', 'Döviz Tahsilat'), ('COLLECTION_HS', 'Has (Altın) Tahsilat'), ('FX_GAIN', 'Kur Farkı Zararı (mağaza zararı kabul)'), ('FX_LOSS', 'Kur Farkı Karı (müşteri aleyhine fark)'), ('DISCOUNT', 'Müşteri İskontosu'), ('WRITEOFF', 'Şüpheli Alacak Silme'), ('CUSTODY_OFFSET', 'Emanet Mahsuplaşması'), ('REVERSAL', 'İptal Karşı Girişi'), ('CORRECTION', 'Sistem Düzeltmesi'), ('OVERPAYMENT', 'Kasa Fazlası (Fazla Tahsilat)')], max_length=20)),
                ('amount_hs', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Has cinsinden tutar (daima pozitif)', max_digits=18)),
                ('amount_hs_signed', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='İşaretli has tutar (yalnız CORRECTION için)', max_digits=18)),
                ('amount_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='İşlem anındaki TL karşılığı (tarihi, sabit)', max_digits=18)),
                ('amount_fx', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Döviz tahsilatlarda orijinal döviz tutarı', max_digits=18)),
                ('exchange_rate_eur', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='1 gr Has = X TL (kaydedilme anındaki, sabit)', max_digits=18)),
                ('fx_to_eur_rate', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Döviz tahsilatlarda 1 birim döviz = X TL (anlık)', max_digits=18)),
                ('currency', models.CharField(choices=[('TRY', 'Türk Lirası'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('HS', 'Has Altın')], default='TRY', max_length=5)),
                ('process_no', models.CharField(blank=True, default='', max_length=100)),
                ('reversal_target_type', models.CharField(blank=True, default='', help_text='REVERSAL kayıtları için: iptal edilen kaydın tipi', max_length=20)),
                ('requires_approval', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_note', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='REVERSAL/FX_GAIN/DISCOUNT için ana ledger satırı', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_entries', to='customers.customerledger')),
                ('related_custody', models.ForeignKey(blank=True, help_text='CUSTODY_OFFSET kayıtlarında bağlı emanet hareketi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_offsets', to='custody.customercustodyledger')),
            ],
            options={
                'db_table': 'CustomerLedger',
                'ordering': ['-created_on'],
            },
        ),
    ]
