# Generated by Django 6.0.4 on 2026-05-09 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('locations', '0001_initial'),
        ('process', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerledger',
            name='related_payment',
            field=models.ForeignKey(blank=True, help_text='Tahsilat kayıtlarında kasaya giren Payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_ledger_entries', to='process.payment'),
        ),
        migrations.AddField(
            model_name='customerledger',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_ledger_entries', to='stores.stores'),
        ),
        migrations.AddField(
            model_name='customers',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city', verbose_name='İl'),
        ),
        migrations.AddField(
            model_name='customers',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.district', verbose_name='İlçe'),
        ),
        migrations.AddField(
            model_name='customers',
            name='store',
            field=models.ManyToManyField(blank=True, related_name='customers', to='stores.stores'),
        ),
        migrations.AddField(
            model_name='customers',
            name='tax_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.taxoffice', verbose_name='Vergi Dairesi'),
        ),
        migrations.AddField(
            model_name='customerledger',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='customers.customers'),
        ),
        migrations.AddIndex(
            model_name='customers',
            index=models.Index(fields=['phone'], name='customers_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='customers',
            index=models.Index(fields=['identification_number'], name='customers_identification_idx'),
        ),
        migrations.AddIndex(
            model_name='customers',
            index=models.Index(fields=['customer_number'], name='customers_customer_number_idx'),
        ),
        migrations.AddIndex(
            model_name='customers',
            index=models.Index(fields=['is_deleted', 'is_active'], name='customers_deleted_active_idx'),
        ),
        migrations.AddIndex(
            model_name='customerledger',
            index=models.Index(fields=['customer', 'is_active'], name='cust_ledger_cust_active_idx'),
        ),
        migrations.AddIndex(
            model_name='customerledger',
            index=models.Index(fields=['process_no'], name='cust_ledger_process_no_idx'),
        ),
        migrations.AddIndex(
            model_name='customerledger',
            index=models.Index(fields=['transaction_type', 'is_active'], name='cust_ledger_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='customerledger',
            index=models.Index(fields=['parent'], name='cust_ledger_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='customerledger',
            index=models.Index(fields=['is_approved', 'requires_approval'], name='cust_ledger_approval_idx'),
        ),
        migrations.AddIndex(
            model_name='customerledger',
            index=models.Index(fields=['related_payment'], name='cust_ledger_payment_idx'),
        ),
        migrations.AddIndex(
            model_name='customerledger',
            index=models.Index(fields=['related_custody'], name='cust_ledger_custody_idx'),
        ),
    ]
