# Generated by Django 6.0.5 on 2026-05-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='identification_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
