# Generated by Django 6.0.4 on 2026-04-28 15:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('user', 'user'), ('customer', 'customer'), ('store', 'store')], max_length=12)),
                ('owner_id', models.CharField(max_length=64)),
                ('channel', models.CharField(choices=[('phone', 'phone'), ('email', 'email')], max_length=10)),
                ('is_consented', models.BooleanField(default=False)),
                ('consented_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(default='otp_verify', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('iys_status', models.CharField(choices=[('pending', 'pending'), ('synced', 'synced'), ('rejected', 'rejected')], default='pending', max_length=10)),
                ('iys_ref', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('user', 'user'), ('store', 'store'), ('customer', 'customer')], max_length=10)),
                ('owner_id', models.CharField(max_length=64)),
                ('channel', models.CharField(choices=[('email', 'email'), ('phone', 'phone')], max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('purpose', models.CharField(choices=[('verify_email', 'verify_email'), ('verify_phone', 'verify_phone'), ('twofa_login', 'twofa_login')], max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('personal_type', models.CharField(blank=True, max_length=120, null=True)),
                ('job_title', models.CharField(blank=True, max_length=120, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('avatar', models.ImageField(blank=True, default='default/user.png', null=True, upload_to='accounts/')),
                ('identification_number', models.CharField(blank=True, max_length=11, null=True)),
                ('is_email_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('is_phone_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('activate_2fa', models.BooleanField(blank=True, default=False, null=True)),
                ('is_blocked', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('is_protected', models.BooleanField(blank=True, default=False, null=True)),
                ('failed_login_attempts', models.IntegerField(default=0, verbose_name='Hatalı Giriş Sayısı')),
                ('blocked_until', models.DateTimeField(blank=True, null=True, verbose_name='Engel Bitiş Tarihi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'db_table': 'Users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
