# Generated by Django 6.0.4 on 2026-05-09 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('roles', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='roles.roles'),
        ),
        migrations.AddField(
            model_name='users',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.stores'),
        ),
        migrations.AddField(
            model_name='users',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='contactconsent',
            index=models.Index(fields=['owner_type', 'owner_id', 'channel'], name='accounts_co_owner_t_95e9a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contactconsent',
            unique_together={('owner_type', 'owner_id', 'channel')},
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['owner_type', 'owner_id', 'purpose', 'channel'], name='accounts_ot_owner_t_524e68_idx'),
        ),
        migrations.AddField(
            model_name='userstoreaccess',
            name='granted_by',
            field=models.ForeignKey(blank=True, help_text='Bu çoklu erişimi atayan üst yönetici (audit için).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Erişimi Veren'),
        ),
        migrations.AddField(
            model_name='userstoreaccess',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Kullanıcının bu özel şubedeki rolü. NULL ise Users.role kullanılır.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_accesses', to='roles.roles', verbose_name='Bu Şubedeki Rol'),
        ),
        migrations.AddField(
            model_name='userstoreaccess',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='stores.stores', verbose_name='Şube'),
        ),
        migrations.AddField(
            model_name='userstoreaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AddIndex(
            model_name='userstoreaccess',
            index=models.Index(fields=['user', 'is_active'], name='usa_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='userstoreaccess',
            index=models.Index(fields=['store', 'is_active'], name='usa_store_active_idx'),
        ),
        migrations.AddIndex(
            model_name='userstoreaccess',
            index=models.Index(fields=['user', 'is_primary'], name='usa_user_primary_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userstoreaccess',
            unique_together={('user', 'store')},
        ),
    ]
