# Generated by Django 6.0.4 on 2026-04-28 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('roles', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='roles.roles'),
        ),
        migrations.AddField(
            model_name='users',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.stores'),
        ),
        migrations.AddField(
            model_name='users',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='contactconsent',
            index=models.Index(fields=['owner_type', 'owner_id', 'channel'], name='accounts_co_owner_t_95e9a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contactconsent',
            unique_together={('owner_type', 'owner_id', 'channel')},
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['owner_type', 'owner_id', 'purpose', 'channel'], name='accounts_ot_owner_t_524e68_idx'),
        ),
    ]
