# Generated by Django 6.0.4 on 2026-05-09 16:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChamberProductPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buy_price_hs', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Dernek Alış Has')),
                ('sale_price_hs', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Dernek Satış Has')),
                ('fixed_labor_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Dernek Sabit İşçilik')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ChamberProductPrices',
            },
        ),
        migrations.CreateModel(
            name='Chambers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Oda/Dernek Adı')),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('website', models.URLField(blank=True, null=True, verbose_name='Web Sitesi')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vergi Numarası')),
                ('registry_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dernek Kütük / Oda Sicil No')),
                ('president_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Oda/Dernek Başkanı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Chambers',
            },
        ),
    ]
