# Generated by Django 6.0.4 on 2026-05-09 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chambers', '0001_initial'),
        ('locations', '0001_initial'),
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chamberproductprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamber_prices', to='products.products'),
        ),
        migrations.AddField(
            model_name='chambers',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chambers', to='locations.city', verbose_name='İl'),
        ),
        migrations.AddField(
            model_name='chambers',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='chambers', to='stores.company', verbose_name='Üye Firmalar'),
        ),
        migrations.AddField(
            model_name='chambers',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chambers', to='locations.district', verbose_name='İlçe'),
        ),
        migrations.AddField(
            model_name='chambers',
            name='president_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presided_chambers', to=settings.AUTH_USER_MODEL, verbose_name='Başkan Kullanıcı Hesabı'),
        ),
        migrations.AddField(
            model_name='chambers',
            name='tax_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chambers', to='locations.taxoffice', verbose_name='Vergi Dairesi'),
        ),
        migrations.AddField(
            model_name='chamberproductprice',
            name='chamber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='chambers.chambers'),
        ),
        migrations.AddIndex(
            model_name='chambers',
            index=models.Index(fields=['is_active'], name='Chambers_is_acti_ab0f03_idx'),
        ),
        migrations.AddIndex(
            model_name='chambers',
            index=models.Index(fields=['name'], name='Chambers_name_95814d_idx'),
        ),
        migrations.AddIndex(
            model_name='chambers',
            index=models.Index(fields=['president_user'], name='chambers_president_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chamberproductprice',
            unique_together={('chamber', 'product')},
        ),
    ]
