# Generated by Django 6.0.4 on 2026-05-09 16:01

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
            ],
            options={
                'verbose_name': 'Paket Modül',
                'verbose_name_plural': 'Paket Modüller',
                'db_table': 'PackageModules',
            },
        ),
        migrations.CreateModel(
            name='PackagePermissionMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(choices=[('manual', 'Elle Atandı'), ('module', 'Modülden Geldi')], default='manual', help_text='Bu yetki pakete elle mi atandı yoksa modülden mi geldi?', max_length=10, verbose_name='Kaynak')),
            ],
            options={
                'db_table': 'PackagePermissionMatrix',
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(help_text='Örn: bronze, silver, gold', unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Paket Adı')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='Sıralama')),
                ('currency', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR')], default='USD', max_length=3, verbose_name='Para Birimi')),
                ('price_license', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Lisans Bedeli (Tek Seferlik)')),
                ('maintenance_percent', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Lisans bedeli üzerinden hesaplanacak yıllık güncelleme/bakım oranı.', max_digits=5, verbose_name='Yıllık Bakım Oranı (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Önerilen')),
                ('badge_text', models.CharField(blank=True, help_text='Örn: "En Popüler"', max_length=30)),
                ('is_demo', models.BooleanField(default=False, help_text='Yalnızca Hızlı Onboarding (Fast-Track) akışı tarafından kullanılır. Bu paket satış listelerinde gösterilmez; gölge sipariş mekanizması tarafından otomatik atanır.', verbose_name='Demo Paketi mi?')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paket',
                'verbose_name_plural': 'Paketler',
                'db_table': 'Packages',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SaaSModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Modül Adı')),
                ('slug', models.SlugField(help_text='URL-safe kısa ad, örn: perakende', max_length=60, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('icon', models.CharField(blank=True, default='fa-solid fa-cube', help_text='FontAwesome class, örn: fa-solid fa-store', max_length=80)),
                ('license_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Modülün tek seferlik lisans satış fiyatı.', max_digits=14, verbose_name='Lisans Bedeli (Tek Seferlik)')),
                ('currency', models.CharField(choices=[('TRY', 'TL'), ('USD', 'Dolar'), ('EUR', 'Euro')], default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='İleriye dönük kiralama modeli için saklı alan.', max_digits=10, verbose_name='Aylık Fiyat (₺)')),
                ('price_yearly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='İleriye dönük kiralama modeli için saklı alan.', max_digits=10, verbose_name='Yıllık Fiyat (₺)')),
                ('is_core', models.BooleanField(default=False, help_text='Çekirdek modüller her pakete dahildir ve kaldırılamaz.', verbose_name='Çekirdek Modül mü?')),
                ('order', models.PositiveSmallIntegerField(default=100, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SaaS Modül',
                'verbose_name_plural': 'SaaS Modüller',
                'db_table': 'SaaSModules',
                'ordering': ('order', 'name'),
            },
        ),
    ]
