# Generated by Django 6.0.4 on 2026-04-28 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagepermissionmatrix',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_matrix', to='roles.permission'),
        ),
        migrations.AddField(
            model_name='packagepermissionmatrix',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perm_matrix', to='packages.packages'),
        ),
        migrations.AddField(
            model_name='packagemodule',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_modules', to='packages.packages', verbose_name='Paket'),
        ),
        migrations.AddField(
            model_name='saasmodule',
            name='dependencies',
            field=models.ManyToManyField(blank=True, help_text='Bu modül seçildiğinde otomatik seçilmesi gereken diğer modüller.', related_name='required_by', to='packages.saasmodule', verbose_name='Bağımlılıklar'),
        ),
        migrations.AddField(
            model_name='saasmodule',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Bu modül satın alındığında müşteriye verilecek sistem yetkileri.', related_name='saas_modules', to='roles.permission', verbose_name='Modül Yetkileri'),
        ),
        migrations.AddField(
            model_name='packagemodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_packages', to='packages.saasmodule', verbose_name='Modül'),
        ),
        migrations.AlterUniqueTogether(
            name='packagepermissionmatrix',
            unique_together={('package', 'permission')},
        ),
        migrations.AlterUniqueTogether(
            name='packagemodule',
            unique_together={('package', 'module')},
        ),
    ]
