# Generated by Django 6.0.4 on 2026-04-28 15:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('backup_file', models.FileField(upload_to='CompanyBackups/')),
                ('file_size', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.CharField(blank=True, max_length=150, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Hazırlanıyor'), ('COMPLETED', 'Tamamlandı'), ('FAILED', 'Hata')], default='COMPLETED', max_length=20)),
            ],
            options={
                'verbose_name': 'Firma Yedeği',
                'verbose_name_plural': 'Firma Yedekleri',
                'db_table': 'CompanyBackup',
                'ordering': ['-created_at'],
            },
        ),
    ]
