# Generated by Django 6.0.4 on 2026-05-09 16:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('backup_file', models.FileField(upload_to='CompanyBackups/')),
                ('file_size', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.CharField(blank=True, max_length=150, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Hazırlanıyor'), ('COMPLETED', 'Tamamlandı'), ('FAILED', 'Hata')], default='COMPLETED', max_length=20)),
            ],
            options={
                'verbose_name': 'Firma Yedeği',
                'verbose_name_plural': 'Firma Yedekleri',
                'db_table': 'CompanyBackup',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestoreAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restore_type', models.CharField(choices=[('FULL', 'Tam Firma Geri Yüklemesi'), ('SMART', 'Akıllı Geri Yükleme (Merge)')], db_index=True, help_text='FULL = wipe & load, SMART = merge / upsert.', max_length=10)),
                ('object_id', models.UUIDField(blank=True, db_index=True, help_text="Smart restore: ilgili kaydın UUID'si.", null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='Smart restore çift yazım koruması için belirleyici anahtar.', max_length=128, null=True)),
                ('original_created_at', models.DateTimeField(blank=True, help_text='Yedekteki orijinal created_at — denetim için dondurulmuş.', null=True)),
                ('original_created_by', models.CharField(blank=True, help_text='Yedekteki orijinal created_by — denetim için dondurulmuş.', max_length=150, null=True)),
                ('restored_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('restore_notes', models.TextField(blank=True, help_text='Restore sonrası özet notlar (kayıt sayısı, atlanan vs.).', null=True)),
                ('similarity_warnings', models.JSONField(blank=True, default=dict, help_text='Şüpheli eşleşmeler için potential_matches listesi.')),
            ],
            options={
                'verbose_name': 'Geri Yükleme Audit Kaydı',
                'verbose_name_plural': 'Geri Yükleme Audit Kayıtları',
                'db_table': 'RestoreAuditLog',
                'ordering': ['-restored_at'],
            },
        ),
        migrations.CreateModel(
            name='ChunkedUploadSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_id', models.UUIDField(db_index=True, help_text='Hedef mağaza UUID — restore bu mağazaya yapılacak.')),
                ('backup_id', models.UUIDField(blank=True, db_index=True, help_text='Opsiyonel: paketin geldiği yedek (audit referans).', null=True)),
                ('filename', models.CharField(help_text='Yüklenen dosyanın orijinal adı.', max_length=255)),
                ('total_size', models.BigIntegerField(help_text='Toplam dosya boyutu (byte).')),
                ('total_chunks', models.IntegerField(help_text='Beklenen toplam parça sayısı.')),
                ('chunk_size', models.IntegerField(help_text='Sabit parça boyutu (byte) — son parça hariç.')),
                ('received_chunks', models.IntegerField(default=0, help_text='Şu ana kadar başarıyla alınan parça sayısı.')),
                ('received_bytes', models.BigIntegerField(default=0, help_text='Şu ana kadar yazılan byte sayısı.')),
                ('temp_file_path', models.CharField(help_text='Sunucuda parçaların append edildiği dosya yolu.', max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('UPLOADING', 'Yükleniyor'), ('READY', 'Tamamlandı (Restore Bekliyor)'), ('COMPLETED', 'Restore Edildi'), ('ABORTED', 'İptal Edildi'), ('FAILED', 'Hata'), ('EXPIRED', 'Süresi Doldu')], db_index=True, default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='FAILED ise hata detayı.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Bu zamandan sonra cleanup task tarafından silinir.')),
                ('user', models.ForeignKey(blank=True, help_text='Yüklemeyi başlatan kullanıcı.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunked_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parçalı Yükleme Oturumu',
                'verbose_name_plural': 'Parçalı Yükleme Oturumları',
                'db_table': 'ChunkedUploadSession',
                'ordering': ['-created_at'],
            },
        ),
    ]
