# Generated by Django 6.0.4 on 2026-05-09 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backups', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companybackup',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='stores.company'),
        ),
        migrations.AddField(
            model_name='restoreauditlog',
            name='backup',
            field=models.ForeignKey(help_text='Bu kaydın geri yüklendiği yedek dosyası.', on_delete=django.db.models.deletion.PROTECT, related_name='restore_logs', to='backups.companybackup'),
        ),
        migrations.AddField(
            model_name='restoreauditlog',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Smart restore: hangi modele ait kayıt yüklendi.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='restoreauditlog',
            name='restored_by',
            field=models.ForeignKey(blank=True, help_text='Geri yüklemeyi tetikleyen kullanıcı.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chunkeduploadsession',
            index=models.Index(fields=['user', 'status'], name='cus_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='chunkeduploadsession',
            index=models.Index(fields=['status', 'expires_at'], name='cus_status_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='restoreauditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='ral_target_idx'),
        ),
        migrations.AddIndex(
            model_name='restoreauditlog',
            index=models.Index(fields=['backup', 'restore_type'], name='ral_backup_type_idx'),
        ),
        migrations.AddIndex(
            model_name='restoreauditlog',
            index=models.Index(fields=['idempotency_key'], name='ral_idempotency_idx'),
        ),
    ]
