# Generated by Django 6.0.4 on 2026-05-09 16:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCustodyLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custody_type', models.CharField(choices=[('IN', 'Emanet Girişi'), ('OUT', 'Emanet Çıkışı'), ('OFFSET', 'Cari Mahsuplaşma'), ('REVERSAL', 'İptal Karşı Girişi'), ('STOCK', 'Stoğa Transfer')], default='IN', max_length=10)),
                ('quantity_piece', models.PositiveIntegerField(default=0)),
                ('quantity_gram', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('amount_hs', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('exchange_rate_eur', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='1 gr Has = X TL (kayıt anındaki, sabit)', max_digits=18)),
                ('amount_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='İşlem anındaki TL karşılığı (raporlama için)', max_digits=18)),
                ('process_no', models.CharField(blank=True, db_index=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_returned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='False ise bakiyeye dahil edilmez (REVERSAL sonrası).')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft-delete: silinmiş kayıt; denetim izi korunur.')),
                ('reverse_reason', models.CharField(blank=True, default='', help_text='REVERSAL kayıtlarında iptal nedeni metni.', max_length=255)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_custody_entries', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CustomerCustodyLedger',
                'ordering': ['-created_on'],
            },
        ),
    ]
