# Generated by Django 6.0.4 on 2026-04-28 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCustodyLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custody_type', models.CharField(choices=[('IN', 'Emanet Girişi'), ('OUT', 'Emanet Çıkışı')], default='IN', max_length=3)),
                ('quantity_piece', models.PositiveIntegerField(default=0)),
                ('quantity_gram', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('amount_hs', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('process_no', models.CharField(blank=True, db_index=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_returned', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CustomerCustodyLedger',
                'ordering': ['-created_on'],
            },
        ),
    ]
