# Generated by Django 6.0.4 on 2026-05-09 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custody', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customercustodyledger',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customers'),
        ),
        migrations.AddField(
            model_name='customercustodyledger',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customercustodyledger',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='REVERSAL/OFFSET/Kısmi OUT için bağlı orijinal emanet kaydı', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_entries', to='custody.customercustodyledger'),
        ),
    ]
