# Generated by Django 6.0.4 on 2026-05-09 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custody', '0002_initial'),
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customercustodyledger',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.products'),
        ),
        migrations.AddField(
            model_name='customercustodyledger',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customercustodyledger',
            name='related_ledger',
            field=models.ForeignKey(blank=True, help_text='OFFSET satırlarında karşılık CustomerLedger satırı', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_offsets', to='customers.customerledger'),
        ),
        migrations.AddField(
            model_name='customercustodyledger',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.stores'),
        ),
        migrations.AddIndex(
            model_name='customercustodyledger',
            index=models.Index(fields=['customer', 'is_returned'], name='custody_cust_returned_idx'),
        ),
        migrations.AddIndex(
            model_name='customercustodyledger',
            index=models.Index(fields=['custody_type'], name='custody_type_idx'),
        ),
        migrations.AddIndex(
            model_name='customercustodyledger',
            index=models.Index(fields=['parent'], name='custody_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='customercustodyledger',
            index=models.Index(fields=['related_ledger'], name='custody_rel_ledger_idx'),
        ),
        migrations.AddIndex(
            model_name='customercustodyledger',
            index=models.Index(fields=['customer', 'is_active', 'is_deleted'], name='custody_active_idx'),
        ),
    ]
