# Generated by Django 6.0.4 on 2026-05-09 16:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('call', 'Telefon Görüşmesi'), ('meeting', 'Yüzyüze/Ziyaret'), ('presentation', 'Sunum'), ('demo', 'Demo Gösterimi'), ('whatsapp', 'WhatsApp/Mesaj'), ('email', 'E-Posta')], default='call', max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('positive', 'Olumlu / İlgilendi'), ('negative', 'Olumsuz / İlgilenmedi'), ('offer_requested', 'Teklif İstedi'), ('offer_decision_pending', 'Teklif Kararı Bekleniyor'), ('demo_requested', 'Demo İstedi'), ('decision_pending', 'Karar Bekleniyor'), ('reached_voicemail', 'Ulaşılamadı'), ('scheduled', 'İleri Tarihe Randevu')], max_length=30, null=True, verbose_name='Sonuç')),
                ('summary', models.TextField(verbose_name='Görüşme Notları / Talepler')),
                ('activity_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Gerçekleşme Zamanı')),
                ('next_action_date', models.DateTimeField(blank=True, null=True, verbose_name='Sonraki Hatırlatma')),
            ],
            options={
                'db_table': 'CRM_LeadActivities',
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_private', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'CRM_LeadNotes',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='LeadStageHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('new', 'Yeni'), ('contacted', 'İletişime Geçildi'), ('qualified', 'Randevu Alındı'), ('proposal', 'Teklif'), ('negotiation', 'Görüşme Aşamasında'), ('won', 'Kazanıldı'), ('lost', 'Kaybedildi'), ('spam', 'Spam'), ('dnc', 'İletişime Geçilmeyecek')], max_length=20, null=True)),
                ('to_status', models.CharField(choices=[('new', 'Yeni'), ('contacted', 'İletişime Geçildi'), ('qualified', 'Randevu Alındı'), ('proposal', 'Teklif'), ('negotiation', 'Görüşme Aşamasında'), ('won', 'Kazanıldı'), ('lost', 'Kaybedildi'), ('spam', 'Spam'), ('dnc', 'İletişime Geçilmeyecek')], max_length=20)),
                ('changed_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'CRM_LeadStageHistory',
                'ordering': ['-changed_on'],
            },
        ),
        migrations.CreateModel(
            name='LeadStateHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('new', 'Yeni'), ('contacted', 'İletişime Geçildi'), ('qualified', 'Uygun Bulundu'), ('proposal', 'Teklif'), ('negotiation', 'Görüşme Aşamasında'), ('won', 'Kazanıldı'), ('lost', 'Kaybedildi'), ('spam', 'Spam'), ('dnc', 'İletişime Geçilmeyecek')], max_length=32)),
                ('note', models.CharField(blank=True, max_length=300, null=True)),
                ('changed_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'CRM_LeadStateHistory',
                'ordering': ['-changed_on'],
            },
        ),
        migrations.CreateModel(
            name='LeadTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'CRM_LeadTags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeadTagMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'CRM_LeadTagMap',
            },
        ),
        migrations.CreateModel(
            name='PackageApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_no', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True)),
                ('first_name', models.CharField(max_length=80, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=80, verbose_name='Soyad')),
                ('phone', models.CharField(max_length=32, verbose_name='Telefon')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='E-Posta')),
                ('business_name', models.CharField(max_length=200, verbose_name='Firma / Mağaza Adı')),
                ('city', models.CharField(blank=True, max_length=64, null=True, verbose_name='İl')),
                ('monthly_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Hesaplanan Aylık Toplam (₺)')),
                ('yearly_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Hesaplanan Yıllık Toplam (₺)')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('contacted', 'İletişime Geçildi'), ('proposal_created', 'Teklif Oluşturuldu'), ('rejected', 'Reddedildi')], default='pending', max_length=20)),
                ('utm_source', models.CharField(blank=True, help_text='Hangi kanaldan geldi? Örn: whatsapp, instagram, google', max_length=100, null=True, verbose_name='UTM Kaynak')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar / Ek Bilgi')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'CRM_PackageApplications',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('business_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Mağaza/Firma Adı')),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('channel', models.CharField(choices=[('field', 'Saha'), ('instagram', 'instagram'), ('facebook', 'facebook'), ('tiktok', 'tiktok'), ('whatsapp', 'whatsapp'), ('website', 'website'), ('referral', 'referans'), ('fast_track', 'Hızlı Kayıt (Demo)'), ('other', 'diğer')], default='instagram', max_length=20)),
                ('channel_handle', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('contacted', 'İletişime Geçildi'), ('qualified', 'Randevu Alındı'), ('proposal', 'Teklif'), ('negotiation', 'Görüşme Aşamasında'), ('won', 'Kazanıldı'), ('lost', 'Kaybedildi'), ('spam', 'Spam'), ('dnc', 'İletişime Geçilmeyecek')], default='new', max_length=20)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, choices=[('store', 'Kuyumcu Mağazası'), ('workshop', 'Kuyumcu Atölyesi'), ('diamond', 'Pırlantacı'), ('silver', 'Gümüşçü'), ('other', 'Diğer')], max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('district', models.CharField(blank=True, max_length=64, null=True)),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Kullanıcılar')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CRM_Leads',
                'ordering': ['-created_on'],
            },
        ),
    ]
