# Generated by Django 6.0.4 on 2026-04-28 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('packages', '0001_initial'),
        ('proposals', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='stores.stores'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadnote',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadnote',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadstagehistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadstagehistory',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadstatehistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadstatehistory',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_history', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadtag',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_tags', to='stores.stores'),
        ),
        migrations.AddField(
            model_name='leadtagmap',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadtagmap',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_maps', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadtagmap',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_maps', to='leads.leadtag'),
        ),
        migrations.AddField(
            model_name='packageapplication',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_applications', to='leads.lead', verbose_name='Bağlı Lead Kaydı'),
        ),
        migrations.AddField(
            model_name='packageapplication',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_applications', to='proposals.proposals', verbose_name='Oluşturulan Teklif'),
        ),
        migrations.AddField(
            model_name='packageapplication',
            name='selected_modules',
            field=models.ManyToManyField(blank=True, related_name='applications', to='packages.saasmodule', verbose_name='Seçilen Modüller'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['store', 'status'], name='CRM_Leads_store_i_493060_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['store', 'channel'], name='CRM_Leads_store_i_5dfc35_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['store', 'created_on'], name='CRM_Leads_store_i_472845_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__isnull', False), ('store__isnull', False)), fields=('store', 'phone'), name='uq_lead_phone_per_store'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), ('store__isnull', False)), fields=('store', 'email'), name='uq_lead_email_per_store'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('phone__isnull', False), ('store__isnull', True)), fields=('phone',), name='uq_lead_phone_global'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), ('store__isnull', True)), fields=('email',), name='uq_lead_email_global'),
        ),
        migrations.AlterUniqueTogether(
            name='leadtag',
            unique_together={('store', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='leadtagmap',
            unique_together={('lead', 'tag')},
        ),
        migrations.AddIndex(
            model_name='packageapplication',
            index=models.Index(fields=['status'], name='CRM_Package_status_7a9426_idx'),
        ),
        migrations.AddIndex(
            model_name='packageapplication',
            index=models.Index(fields=['phone'], name='CRM_Package_phone_b24d31_idx'),
        ),
        migrations.AddIndex(
            model_name='packageapplication',
            index=models.Index(fields=['created_on'], name='CRM_Package_created_4015d2_idx'),
        ),
    ]
