# Generated by Django 6.0.4 on 2026-05-09 16:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
        ('products', '0001_initial'),
        ('stock_management', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_no', models.CharField(blank=True, db_index=True, help_text='TRF-2026-0001 formatında otomatik üretilir. DRAFT aşamasında NULL kalabilir.', max_length=30, null=True, unique=True, verbose_name='Transfer No')),
                ('transfer_type', models.CharField(choices=[('CASH', 'Yalnız Nakit/Döviz/HS'), ('STOCK', 'Yalnız Stok (Ürün/Gram)'), ('MIXED', 'Karma (Nakit + Stok)')], db_index=True, default='MIXED', max_length=10, verbose_name='Transfer Tipi')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak (Henüz gönderilmedi)'), ('IN_TRANSIT', 'Yolda (Kabul Bekliyor)'), ('ACCEPTED', 'Tamamı Kabul Edildi'), ('PARTIALLY_ACCEPTED', 'Kısmen Kabul Edildi'), ('REJECTED', 'Reddedildi (Geri Döndü)'), ('CANCELLED', 'İptal Edildi (DRAFT iptali)')], db_index=True, default='DRAFT', max_length=20, verbose_name='Durum')),
                ('notes_sender', models.TextField(blank=True, default='', help_text='Gönderen şubenin transfere eklediği açıklama.', verbose_name='Gönderen Notları')),
                ('notes_receiver', models.TextField(blank=True, default='', help_text='Kabul/red sırasında girilen not. REJECTED durumunda ZORUNLUDUR.', verbose_name='Alan Şube Notları / Red Sebebi')),
                ('notes_admin', models.TextField(blank=True, default='', help_text='Süresi geçmiş transferleri patron manuel REJECTED yaparken zorunlu gerekçe.', verbose_name='Yönetici Müdahale Notu')),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Taslak Oluşturma Zamanı')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True, verbose_name='Yola Çıkış Zamanı')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Zamanı (ACCEPTED/REJECTED)')),
                ('expected_arrival_date', models.DateField(blank=True, help_text='Bu tarihten sonra transfer hâlâ IN_TRANSIT ise sistem uyarı üretir.', null=True, verbose_name='Tahmini Varış Tarihi')),
                ('is_reversed', models.BooleanField(default=False, help_text='REJECTED veya manuel reversal sonrası True olur. Append-Only ihlali değildir; denormalize bayrak.', verbose_name='İptal Edildi mi?')),
                ('total_cash_tl_equivalent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Hızlı liste görünümü için TransferItem toplamı. Otorite TransferItem satırlarıdır.', max_digits=18, verbose_name='Toplam Nakit (TL Karşılığı)')),
                ('total_stock_hs', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Stok kalemlerinin Has-altın karşılığı toplamı (özetleme için).', max_digits=18, verbose_name='Toplam Stok (HS)')),
                ('line_count', models.PositiveIntegerField(default=0, help_text='StoreTransferItem satır sayısı (cache).', verbose_name='Kalem Sayısı')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Kabul Eden')),
                ('destination_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_transfers', to='stores.stores', verbose_name='Alan Şube')),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Yola Çıkaran (DRAFT→IN_TRANSIT)')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Transferi Başlatan')),
                ('parent_transfer', models.ForeignKey(blank=True, help_text='Kısmi kabul sonrasında reddedilen kalemler için yeni bir transfer açılırsa, ana transfere bağlanır.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_transfers', to='store_transfers.storetransfer', verbose_name='Üst Transfer (Kısmi Kabul Sonrası)')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Reddeden')),
                ('source_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_transfers', to='stores.stores', verbose_name='Gönderen Şube')),
            ],
            options={
                'verbose_name': 'Şube Transferi',
                'verbose_name_plural': 'Şube Transferleri',
                'db_table': 'StoreTransfers',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='StoreTransferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('CASH', 'Nakit / Döviz / HS'), ('STOCK', 'Stok (Ürün veya Gram)')], db_index=True, max_length=10, verbose_name='Kalem Tipi')),
                ('currency', models.CharField(blank=True, choices=[('TRY', 'Türk Lirası'), ('USD', 'Amerikan Doları'), ('EUR', 'Euro'), ('GBP', 'İngiliz Sterlini'), ('HS', 'Has Altın (gram)')], help_text="item_type='CASH' ise zorunlu; aksi halde NULL.", max_length=3, null=True, verbose_name='Para Birimi')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='CASH için tutar (TRY/USD/EUR/GBP/HS). HS için decimal_places=2 yerine TransferItem.amount_hs uygulamalıdır; bu alan genel kullanım içindir.', max_digits=18, null=True, verbose_name='Miktar')),
                ('amount_eur_equivalent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Kur dalgalanmasından bağımsız, gönderim anındaki TL karşılığı.', max_digits=18, verbose_name='TL Karşılığı (gönderim anında)')),
                ('exchange_rate_at_dispatch', models.DecimalField(blank=True, decimal_places=4, help_text='currency=TRY için NULL; diğer döviz/HS için tarihsel sabit kur.', max_digits=12, null=True, verbose_name='Gönderim Kuru')),
                ('quantity_pieces', models.PositiveIntegerField(default=0, help_text='Barkodlu/parçalı ürünler için. Gramajlı altında 0.', verbose_name='Adet')),
                ('quantity_gram', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Gramajlı altın/bilezik için. Barkodlu parça ürünlerde 0.', max_digits=18, verbose_name='Gram')),
                ('unit_cost_hs', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Kaynak şubedeki StockSnapshot.weighted_avg_cost_hs değeri kopyalanır. Hedef WAC hesaplamasının girdisi.', max_digits=18, verbose_name='Birim Maliyet (HS)')),
                ('unit_cost_eur', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Kaynak şubedeki WAC TL değeri (tarihsel kopya).', max_digits=18, verbose_name='Birim Maliyet (TL)')),
                ('item_status', models.CharField(choices=[('PENDING', 'Beklemede'), ('ACCEPTED', 'Kabul Edildi'), ('REJECTED', 'Reddedildi')], db_index=True, default='PENDING', max_length=10, verbose_name='Kalem Durumu')),
                ('accepted_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Kısmi kabul senaryosu için. Tam kabulde amount ile eşit, redde 0.', max_digits=18, null=True, verbose_name='Kabul Edilen Tutar (CASH)')),
                ('accepted_pieces', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kabul Edilen Adet (STOCK)')),
                ('accepted_gram', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='Kabul Edilen Gram (STOCK)')),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Red Sebebi')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('destination_bank_account', models.ForeignKey(blank=True, help_text='Accept anında çözülür. NULL ise alan şubenin currency-eşleşen ilk CASH hesabı kullanılır.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_transfer_items', to='banking.bankaccount', verbose_name='Hedef Kasa (CASH)')),
                ('destination_cashbox_ledger', models.ForeignKey(blank=True, help_text='ACCEPTED yazımındaki TRANSFER_IN girdisinin FK referansı.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_item_destinations', to='banking.cashboxledger', verbose_name='Hedef Kasa Defteri Satırı')),
                ('destination_stock_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_item_destinations', to='stock_management.stockledger', verbose_name='Hedef Stok Defteri Satırı')),
                ('product', models.ForeignKey(blank=True, help_text="item_type='STOCK' ise zorunlu.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items', to='products.products', verbose_name='Ürün')),
                ('source_bank_account', models.ForeignKey(blank=True, help_text='CASH item için DRAFT aşamasında zorunlu. Hangi kasadan çıkacak?', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbound_transfer_items', to='banking.bankaccount', verbose_name='Kaynak Kasa (CASH)')),
                ('source_cashbox_ledger', models.ForeignKey(blank=True, help_text='IN_TRANSIT yazımındaki TRANSFER_OUT girdisinin FK referansı.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_item_sources', to='banking.cashboxledger', verbose_name='Kaynak Kasa Defteri Satırı')),
                ('source_stock_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_item_sources', to='stock_management.stockledger', verbose_name='Kaynak Stok Defteri Satırı')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store_transfers.storetransfer', verbose_name='Üst Transfer')),
            ],
            options={
                'verbose_name': 'Transfer Kalemi',
                'verbose_name_plural': 'Transfer Kalemleri',
                'db_table': 'StoreTransferItems',
                'ordering': ['transfer_id', 'created_on'],
            },
        ),
        migrations.AddIndex(
            model_name='storetransfer',
            index=models.Index(fields=['source_store', 'status'], name='st_source_status_idx'),
        ),
        migrations.AddIndex(
            model_name='storetransfer',
            index=models.Index(fields=['destination_store', 'status'], name='st_dest_status_idx'),
        ),
        migrations.AddIndex(
            model_name='storetransfer',
            index=models.Index(fields=['status', 'created_on'], name='st_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='storetransfer',
            index=models.Index(fields=['transfer_no'], name='st_transfer_no_idx'),
        ),
        migrations.AddConstraint(
            model_name='storetransfer',
            constraint=models.CheckConstraint(condition=models.Q(('source_store', models.F('destination_store')), _negated=True), name='st_source_neq_dest'),
        ),
        migrations.AddIndex(
            model_name='storetransferitem',
            index=models.Index(fields=['transfer', 'item_type'], name='sti_transfer_type_idx'),
        ),
        migrations.AddIndex(
            model_name='storetransferitem',
            index=models.Index(fields=['transfer', 'item_status'], name='sti_transfer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='storetransferitem',
            index=models.Index(fields=['product'], name='sti_product_idx'),
        ),
    ]
