# Generated by Django 6.0.4 on 2026-05-09 16:01

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Benzersiz saglayici adi. Ornek: harem_altin, grand_bazaar, cbrt', max_length=100, unique=True, verbose_name='Saglayici Adi')),
                ('display_name', models.CharField(help_text='Kullaniciya gosterilecek isim. Ornek: Harem Altin API', max_length=200, verbose_name='Gorunen Ad')),
                ('provider_type', models.CharField(default='api', help_text="'api' (REST API), 'websocket' (WS), 'scraper' (HTML parse), 'manual' (elle giris)", max_length=50, verbose_name='Saglayici Tipi')),
                ('base_url', models.URLField(blank=True, default='', help_text='API temel adresi. Ornek: https://api.haremaltin.com/v1', max_length=500, verbose_name='API Base URL')),
                ('api_key_setting', models.CharField(blank=True, default='', help_text='Django settings dosyasindaki API key degisken adi. Ornek: HAREMALTIN_API_KEY (settings.HAREMALTIN_API_KEY olarak cekilir)', max_length=100, verbose_name='API Key Settings Adi')),
                ('api_secret_setting', models.CharField(blank=True, default='', help_text='Django settings dosyasindaki API secret degisken adi.', max_length=100, verbose_name='API Secret Settings Adi')),
                ('extra_headers', models.JSONField(blank=True, default=dict, help_text='JSON formatinda ek basliklar. Ornek: {"x-rapidapi-host": "..."}', verbose_name='Ek HTTP Baslik Bilgileri')),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='Saglayiciya ozel ek ayarlar. Ornek: {"timeout": 10, "retry_count": 3, "rate_limit_per_min": 30}', verbose_name='Ek Konfigurasyon')),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='Dusuk numara = yuksek oncelik. Failover sirasini belirler. 1 en yuksek.', verbose_name='Oncelik')),
                ('poll_interval_seconds', models.PositiveIntegerField(default=60, help_text='Bu API kac saniyede bir sorgulanacak', verbose_name='Sorgulama Araligi (sn)')),
                ('cache_ttl_seconds', models.PositiveIntegerField(default=30, help_text='Redis cache te bu API nin fiyatlari kac saniye gecerli kalacak', verbose_name='Cache Suresi (sn)')),
                ('timeout_seconds', models.PositiveIntegerField(default=10, help_text='API cagrisinin maksimum bekleme suresi', verbose_name='Timeout (sn)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('INACTIVE', 'Pasif'), ('ERROR', 'Hata'), ('MAINTENANCE', 'Bakim')], default='ACTIVE', max_length=20, verbose_name='Durum')),
                ('last_success_at', models.DateTimeField(blank=True, help_text='Bu API den en son ne zaman basarili fiyat alindi', null=True, verbose_name='Son Basarili Cagri')),
                ('last_error_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Hata Zamani')),
                ('last_error_message', models.TextField(blank=True, default='', verbose_name='Son Hata Mesaji')),
                ('consecutive_errors', models.PositiveIntegerField(default=0, help_text='Ust uste kac kere hata alindi. Basarili cekim sifirlar.', verbose_name='Ardisik Hata Sayisi')),
                ('max_consecutive_errors', models.PositiveIntegerField(default=5, help_text='Bu sayiya ulasilirsa saglayici otomatik ERROR durumuna gecer', verbose_name='Maks Ardisik Hata')),
                ('is_active', models.BooleanField(default=True, help_text='False ise bu saglayicidan fiyat cekilmez', verbose_name='Aktif Mi')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Olusturma Tarihi')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Son Guncelleme')),
            ],
            options={
                'verbose_name': 'Fiyat Saglayici',
                'verbose_name_plural': 'Fiyat Saglayicilar',
                'db_table': 'PriceProvider',
                'ordering': ['priority', 'name'],
                'indexes': [models.Index(fields=['is_active', 'priority'], name='priceprov_active_priority_idx'), models.Index(fields=['status'], name='priceprov_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceProviderMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_code', models.CharField(help_text='API den gelen ham kod. Ornek: ALTIN, ALTINTRY, XAU/TRY, HAS_GOLD', max_length=50, verbose_name='Kaynak Kodu')),
                ('target_metal_type', models.CharField(choices=[('GOLD_24K', 'Has Altin (24 Ayar)'), ('GOLD_22K', '22 Ayar Altin'), ('GOLD_18K', '18 Ayar Altin'), ('GOLD_14K', '14 Ayar Altin'), ('GOLD_8K', '8 Ayar Altin'), ('SILVER', 'Gumus (Generic)'), ('SILVER_999', 'Has Gumus (999 Ayar)'), ('SILVER_925', '925 Ayar Gumus (Sterling)'), ('PLATINUM', 'Platin'), ('PALLADIUM', 'Paladyum'), ('USD', 'Amerikan Dolari'), ('EUR', 'Euro'), ('GBP', 'Ingiliz Sterlini')], help_text='Sistemdeki standart metal/doviz kodu', max_length=20, verbose_name='Hedef Metal Tipi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('buy_field_name', models.CharField(default='buy', help_text='API JSON cevabindaki alis fiyati alan adi. Ornek: buy, alis, buyPrice', max_length=50, verbose_name='Alis Fiyati Alan Adi')),
                ('sell_field_name', models.CharField(default='sell', help_text='API JSON cevabindaki satis fiyati alan adi. Ornek: sell, satis, sellPrice', max_length=50, verbose_name='Satis Fiyati Alan Adi')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='stock_management.priceprovider', verbose_name='Saglayici')),
            ],
            options={
                'verbose_name': 'Fiyat Eslestirme',
                'verbose_name_plural': 'Fiyat Eslestirmeleri',
                'db_table': 'PriceProviderMapping',
                'ordering': ['provider', 'source_code'],
                'indexes': [models.Index(fields=['provider', 'is_active'], name='pricemapping_prov_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'source_code'), name='pricemapping_unique_prov_source')],
            },
        ),
        migrations.CreateModel(
            name='PriceQuote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('metal_type', models.CharField(choices=[('GOLD_24K', 'Has Altin (24 Ayar)'), ('GOLD_22K', '22 Ayar Altin'), ('GOLD_18K', '18 Ayar Altin'), ('GOLD_14K', '14 Ayar Altin'), ('GOLD_8K', '8 Ayar Altin'), ('SILVER', 'Gumus (Generic)'), ('SILVER_999', 'Has Gumus (999 Ayar)'), ('SILVER_925', '925 Ayar Gumus (Sterling)'), ('PLATINUM', 'Platin'), ('PALLADIUM', 'Paladyum'), ('USD', 'Amerikan Dolari'), ('EUR', 'Euro'), ('GBP', 'Ingiliz Sterlini')], max_length=20, verbose_name='Metal / Doviz Tipi')),
                ('currency_code', models.CharField(help_text='API den gelen orijinal kod. Ornek: ALTIN, ALTINTRY, USDTRY, HAS_ALTIN, 22_AYAR', max_length=20, verbose_name='Para Birimi Kodu')),
                ('quote_type', models.CharField(choices=[('SPOT', 'Anlik / Spot'), ('DAILY_OPEN', 'Gunluk Acilis'), ('DAILY_CLOSE', 'Gunluk Kapanis'), ('MANUAL', 'Manuel Giris')], default='SPOT', max_length=20, verbose_name='Fiyat Tipi')),
                ('buy_price_eur', models.DecimalField(decimal_places=4, help_text='Alis fiyati TL cinsinden', max_digits=15, verbose_name='Alis (TL)')),
                ('sell_price_eur', models.DecimalField(decimal_places=4, help_text='Satis fiyati TL cinsinden', max_digits=15, verbose_name='Satis (TL)')),
                ('buy_price_hs', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Alis fiyati Has cinsinden (Has Altin bazinda normalize edilmis)', max_digits=12, verbose_name='Alis (Has)')),
                ('sell_price_hs', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), help_text='Satis fiyati Has cinsinden (Has Altin bazinda normalize edilmis)', max_digits=12, verbose_name='Satis (Has)')),
                ('spread_eur', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Alis-satis farki TL cinsinden (sell - buy)', max_digits=12, verbose_name='Spread (TL)')),
                ('change_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='API den gelen yuzde degisim', max_digits=8, verbose_name='Degisim Orani (%)')),
                ('raw_data', models.JSONField(blank=True, help_text='API cevabinin orjinal hali (debug ve audit icin)', null=True, verbose_name='Ham API Verisi')),
                ('quoted_at', models.DateTimeField(help_text='Fiyatin gecerli oldugu an (API den gelen veya alinma zamani)', verbose_name='Fiyat Zamani')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Kayit Zamani')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='stock_management.priceprovider', verbose_name='Fiyat Saglayici')),
            ],
            options={
                'verbose_name': 'Fiyat Kaydi',
                'verbose_name_plural': 'Fiyat Kayitlari',
                'db_table': 'PriceQuote',
                'ordering': ['-quoted_at'],
                'indexes': [models.Index(fields=['metal_type', '-quoted_at'], name='pricequote_metal_date_idx'), models.Index(fields=['provider', 'metal_type', '-quoted_at'], name='pricequote_prov_metal_date_idx'), models.Index(fields=['currency_code', '-quoted_at'], name='pricequote_curcode_date_idx'), models.Index(fields=['created_on'], name='pricequote_created_on_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('IN', 'Giris'), ('OUT', 'Cikis')], help_text='IN = stok artisi, OUT = stok azalisi', max_length=3, verbose_name='Yon')),
                ('reason', models.CharField(choices=[('PURCHASE', 'Tedarikci Alisi'), ('SALE', 'Satis'), ('RETURN_IN', 'Satis Iadesi (Giris)'), ('RETURN_OUT', 'Alis Iadesi (Cikis)'), ('CONV_OUT', 'Donusum Cikisi (Kaynak)'), ('CONV_IN', 'Donusum Girisi (Hedef)'), ('XFER_OUT', 'Transfer Cikis'), ('XFER_IN', 'Transfer Giris'), ('ADJ_PLUS', 'Duzeltme Giris (Fazla)'), ('ADJ_MINUS', 'Duzeltme Cikis (Eksik)'), ('INITIAL', 'Acilis Sayimi'), ('SCRAP_MELT', 'Eritme / Isleme Fire'), ('REPAIR_IN', 'Tamir Giris'), ('REPAIR_OUT', 'Tamir Cikis'), ('CUSTODY_IN', 'Emanet Alındı (Giriş)'), ('CUSTODY_OUT', 'Emanet Teslim (Çıkış)'), ('CUSTODY_2_STK', 'Emanet → Serbest Stok'), ('PAYMENT_IN', 'Ürün ile Tahsilat (Müşteriden Alındı)'), ('PAYMENT_OUT', 'Ürün ile Ödeme (Müşteriye Verildi)')], help_text='Hareketin neden yapildigini belirten kod', max_length=20, verbose_name='Sebep')),
                ('quantity_pieces', models.PositiveIntegerField(default=0, help_text='Hareket miktari adet. Barkodlu urunler icin.', verbose_name='Miktar (Adet)')),
                ('quantity_gram', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Hareket miktari gram. Hurda, bilezik, kulce icin.', max_digits=14, verbose_name='Miktar (Gram)')),
                ('unit_cost_hs', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Islem anindaki birim Has maliyeti. Cikislarda WAC muhurlenir.', max_digits=12, verbose_name='Birim Maliyet (Has)')),
                ('unit_cost_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Islem anindaki birim TL maliyeti.', max_digits=15, verbose_name='Birim Maliyet (TL)')),
                ('hs_rate_eur', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Islem anindaki Has Altin TL kuru (tarihsel referans).', max_digits=14, verbose_name='Has/TL Kuru')),
                ('ref_type', models.CharField(db_index=True, help_text="Ust islem turu: 'process', 'conversion', 'invoice', 'transfer', 'count', 'adjustment', 'initial', 'legacy'", max_length=30, verbose_name='Referans Tipi')),
                ('ref_id', models.CharField(db_index=True, help_text='Ilgili kaydin UUID veya process_no degeri', max_length=64, verbose_name='Referans ID')),
                ('notes', models.TextField(blank=True, default='', help_text='Hareket hakkinda serbest metin aciklama', verbose_name='Aciklama')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Islem Tarihi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_ledger_entries', to=settings.AUTH_USER_MODEL, verbose_name='Islemi Yapan')),
                ('paired_entry', models.OneToOneField(blank=True, help_text='Donusum islemlerinde kaynak (OUT) ve hedef (IN) satirlarini birbirine baglar. Tek bir donusum isleminin iki tarafini izlemek icindir.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_with', to='stock_management.stockledger', verbose_name='Eslestirilmis Kayit')),
                ('product', models.ForeignKey(help_text='Hareketin ait oldugu urun. PROTECT: urun silinirse hata verir.', on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='products.products', verbose_name='Urun')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='stores.stores', verbose_name='Magaza')),
            ],
            options={
                'verbose_name': 'Stok Hareket Logu',
                'verbose_name_plural': 'Stok Hareket Loglari',
                'db_table': 'StockLedger',
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['product', 'store', '-created_on'], name='sl_prod_store_date_idx'), models.Index(fields=['store', 'reason', '-created_on'], name='sl_store_reason_date_idx'), models.Index(fields=['ref_type', 'ref_id'], name='sl_ref_idx'), models.Index(fields=['store', 'direction', '-created_on'], name='sl_store_dir_date_idx'), models.Index(fields=['created_by', '-created_on'], name='sl_user_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_gram__gte', Decimal('0.0000'))), name='stock_ledger_positive_gram'), models.CheckConstraint(condition=models.Q(('quantity_pieces__gte', 0)), name='stock_ledger_positive_pieces')],
            },
        ),
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stock_pieces', models.IntegerField(default=0, help_text='Mevcut adet stok. Barkodlu urunler icin.', verbose_name='Stok (Adet)')),
                ('stock_gram', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Mevcut gram stok. Hurda, bilezik, kulce icin.', max_digits=14, verbose_name='Stok (Gram)')),
                ('custody_gram', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Müşteri emaneti gram stok. Mağaza satılabilir stoğunun PARÇASI DEĞİLDİR. Sadece Emanet Yönetimi ekranında görünür.', max_digits=14, verbose_name='Emanet Stok (Gram)')),
                ('custody_pieces', models.IntegerField(default=0, help_text='Müşteri emaneti adet stok. Mağaza satılabilir stoğunun PARÇASI DEĞİLDİR. Sadece Emanet Yönetimi ekranında görünür.', verbose_name='Emanet Stok (Adet)')),
                ('weighted_avg_cost_hs', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Agirlikli ortalama alis maliyeti (Has Altin cinsinden)', max_digits=12, verbose_name='WAC Has')),
                ('weighted_avg_cost_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Agirlikli ortalama alis maliyeti (TL cinsinden)', max_digits=15, verbose_name='WAC TL')),
                ('incoming_stock_pieces', models.IntegerField(default=0, help_text='Siparis verilmis ama henuz teslim alinmamis adet', verbose_name='Bekleyen Stok (Adet)')),
                ('incoming_stock_gram', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Siparis verilmis ama henuz teslim alinmamis gram', max_digits=14, verbose_name='Bekleyen Stok (Gram)')),
                ('use_custom_pricing', models.BooleanField(default=False, help_text='True ise bu magaza icin asagidaki ozel fiyatlar kullanilir', verbose_name='Ozel Fiyat Kullan')),
                ('custom_buy_price_hs', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), help_text='Magaza ozel alis fiyati (Has cinsinden)', max_digits=10, null=True, verbose_name='Ozel Alis Has')),
                ('custom_sale_price_hs', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), help_text='Magaza ozel satis fiyati (Has cinsinden)', max_digits=10, null=True, verbose_name='Ozel Satis Has')),
                ('custom_fixed_labor', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Magaza ozel sabit iscilik tutari', max_digits=12, null=True, verbose_name='Ozel Sabit Iscilik')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Son Guncelleme')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Olusturma Tarihi')),
                ('product', models.ForeignKey(help_text='Stok takibi yapilan urun', on_delete=django.db.models.deletion.PROTECT, related_name='stock_snapshots', to='products.products', verbose_name='Urun')),
                ('store', models.ForeignKey(help_text='Stogun tutuldugu magaza', on_delete=django.db.models.deletion.CASCADE, related_name='stock_snapshots', to='stores.stores', verbose_name='Magaza')),
            ],
            options={
                'verbose_name': 'Stok Snapshot',
                'verbose_name_plural': 'Stok Snapshot Kayitlari',
                'db_table': 'StockSnapshot',
                'ordering': ['-updated_on'],
                'indexes': [models.Index(fields=['store', 'product'], name='stksnapshot_store_product_idx'), models.Index(fields=['store'], name='stksnapshot_store_idx'), models.Index(fields=['product'], name='stksnapshot_product_idx')],
                'constraints': [models.UniqueConstraint(fields=('store', 'product'), name='stock_snapshot_unique_store_product'), models.CheckConstraint(condition=models.Q(('stock_gram__gte', Decimal('0.0000'))), name='stock_snapshot_no_negative_gram'), models.CheckConstraint(condition=models.Q(('stock_pieces__gte', 0)), name='stock_snapshot_no_negative_pieces'), models.CheckConstraint(condition=models.Q(('custody_gram__gte', Decimal('0.0000'))), name='stock_snapshot_no_negative_custody_gram'), models.CheckConstraint(condition=models.Q(('custody_pieces__gte', 0)), name='stock_snapshot_no_negative_custody_pieces')],
            },
        ),
    ]
