# Generated by Django 6.0.4 on 2026-04-28 15:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('created_on', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ActivityLogs',
                'indexes': [models.Index(fields=['created_by'], name='activitylogs_created_by_idx'), models.Index(fields=['-created_on'], name='actlogs_cre_desc_idx'), models.Index(fields=['is_deleted'], name='activitylogs_is_deleted_idx')],
            },
        ),
    ]
