# Generated by Django 6.0.4 on 2026-04-28 15:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(db_index=True, help_text='ERP içindeki takip no (Örn: 20260001)', max_length=32)),
                ('document_number', models.CharField(blank=True, db_index=True, help_text='Resmi GİB Numarası (Örn: GIB202600000001)', max_length=16, null=True)),
                ('ettn', models.UUIDField(blank=True, help_text='GİB Evrensel Tekil Tanımlama Numarası', null=True)),
                ('sequence_no', models.PositiveIntegerField()),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Vade Tarihi')),
                ('invoice_type', models.CharField(choices=[('SALE', 'Satış'), ('PURCHASE', 'Alış'), ('RETURN', 'İade'), ('SERVICE', 'Hizmet')], default='SALE', max_length=12)),
                ('doc_class', models.CharField(choices=[('PROFORMA', 'Proforma / Ön Fatura'), ('E_INVOICE', 'E-Fatura'), ('E_ARCHIVE', 'E-Arşiv Fatura'), ('EXPENSE', 'Gider Pusulası'), ('PAPER', 'Kağıt Fatura')], default='PROFORMA', max_length=20)),
                ('scenario', models.CharField(choices=[('TEMELFATURA', 'Temel Fatura'), ('TICARIFATURA', 'Ticari Fatura'), ('EARSIVFATURA', 'E-Arşiv Fatura'), ('EARSIVINTERNET', 'E-Arşiv (İnternet Satışı)')], default='TEMELFATURA', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak / Proforma'), ('QUEUED', 'Gönderim Sırasında'), ('ISSUED', 'Kesildi (Resmileşti)'), ('SENT', 'GİB’e Gönderildi'), ('APPROVED', 'Onaylandı (GİB/Müşteri)'), ('REJECTED', 'Reddedildi'), ('CANCELED', 'İptal Edildi'), ('ERROR', 'Hata Aldı')], default='DRAFT', max_length=12)),
                ('currency', models.CharField(choices=[('TRY', 'Türk Lirası'), ('USD', 'Amerikan Doları'), ('EUR', 'Euro'), ('HS', 'Has Altın')], default='TRY', max_length=8)),
                ('exrate_to_try', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=14)),
                ('hs_to_try', models.DecimalField(blank=True, decimal_places=6, help_text='İşlem anındaki Has Altın kuru', max_digits=14, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tax_breakdown', models.JSONField(blank=True, default=dict, null=True)),
                ('paid_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('is_einvoice', models.BooleanField(default=False)),
                ('gib_uuid', models.CharField(blank=True, default='', max_length=36)),
                ('gib_status_code', models.CharField(blank=True, default='', help_text='GİB Durum Kodu (1000, 1200, 1300)', max_length=10)),
                ('gib_status_desc', models.CharField(blank=True, default='', max_length=255)),
                ('gib_error', models.TextField(blank=True, default='')),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='Invoices/xml/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='Invoices/pdf/')),
                ('html_content', models.TextField(blank=True, help_text='Önizleme için HTML', null=True)),
                ('pavo_sale_number', models.CharField(blank=True, default='', max_length=64)),
                ('pavo_invoice_no', models.CharField(blank=True, default='', max_length=64)),
                ('pavo_sale_data', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Invoices',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_id', models.UUIDField(blank=True, db_index=True, help_text='InvoiceSyncLog ile bağlantı kurmak için ortak izleme kimliği', null=True)),
                ('log_number', models.CharField(db_index=True, help_text='Kullanıcıya gösterilecek referans numarası (Örn: LOG-20260416-0042)', max_length=20, unique=True)),
                ('level', models.CharField(choices=[('INFO', 'Bilgi'), ('WARN', 'Uyarı'), ('ERROR', 'Hata')], default='INFO', max_length=5)),
                ('event', models.CharField(choices=[('SEND_ATTEMPT', 'Gönderim Denemesi'), ('GIB_ERROR', 'GİB Hatası'), ('GIB_SUCCESS', 'GİB Başarılı'), ('STATUS_CHANGE', 'Durum Değişikliği'), ('DRAFT_RESET', 'Düzenlemeye Alındı'), ('VALIDATION_ERROR', 'Doğrulama Hatası'), ('CANCEL', 'İptal')], max_length=20)),
                ('user_message', models.CharField(help_text='Kullanıcıya gösterilecek sanitize edilmiş mesaj', max_length=500)),
                ('is_resolved', models.BooleanField(default=False, help_text="Admin tarafından 'çözüldü' olarak işaretlenebilir")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'InvoiceActivityLogs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('barcode', models.CharField(blank=True, default='', max_length=50)),
                ('jewelry_type', models.CharField(blank=True, default='', max_length=100)),
                ('is_gram_bullion', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('unit', models.CharField(choices=[('GR', 'Gram'), ('AD', 'Adet'), ('CM', 'Santim'), ('KG', 'Kilogram')], default='GR', max_length=4)),
                ('unit_price', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15)),
                ('price_hs', models.DecimalField(blank=True, decimal_places=3, help_text='Birim Has Fiyatı', max_digits=12, null=True)),
                ('hs_to_try', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('withholding_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tevkifat Oranı (Varsa)', max_digits=5)),
                ('withholding_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_excl_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_incl_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('exemption_reason', models.CharField(blank=True, default='', help_text='İstisna gerekçesi (Örn: KDVK Madde 17/4-g — Külçe altın teslimi)', max_length=255)),
                ('notes', models.CharField(blank=True, default='', help_text='Satır açıklaması (Örn: KDVK 17/4-g)', max_length=255)),
            ],
            options={
                'db_table': 'InvoiceItems',
            },
        ),
        migrations.CreateModel(
            name='InvoicePaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'InvoicePaymentAllocations',
            },
        ),
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('seq_type', models.CharField(choices=[('INV', 'Fatura Serisi'), ('EXP', 'Gider Pusulası Serisi'), ('PRF', 'Proforma Serisi')], default='INV', max_length=3)),
                ('last_no', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('SEND_TO_ESUREC', "e-Süreç'e Gönder"), ('SEND_TO_GIB', "GİB'e Gönder"), ('CHECK_STATUS', 'Durum Sorgula'), ('GET_PDF', 'PDF Al'), ('GET_XML', 'XML Al'), ('CANCEL', 'İptal')], max_length=20)),
                ('status', models.CharField(choices=[('QUEUED', 'Kuyrukta'), ('PROCESSING', 'İşleniyor'), ('SUCCESS', 'Başarılı'), ('FAILED', 'Başarısız'), ('SKIPPED', 'Atlandı'), ('RETRYING', 'Tekrar Deneniyor')], default='QUEUED', max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Celery Task ID')),
                ('attempt', models.IntegerField(default=1, verbose_name='Deneme Sayısı')),
                ('esurec_invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'InvoiceSyncLogs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreEInvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('integrator_name', models.CharField(blank=True, default='GIB', max_length=50)),
                ('api_username', models.CharField(blank=True, max_length=100, null=True)),
                ('api_password', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_balance', models.PositiveIntegerField(blank=True, default=250, null=True)),
                ('last_topup_at', models.DateTimeField(blank=True, null=True)),
                ('default_invoice_product_name', models.CharField(blank=True, default='24 Ayar Has Altın', help_text='Toplu banka-fatura akışında metal kaleminin ürün adı (Örn: "24 Ayar Has Altın", "Muhtelif Takı").', max_length=150, verbose_name='Varsayılan Ürün Adı')),
                ('default_invoice_karat', models.PositiveSmallIntegerField(choices=[(24, '24 Ayar'), (22, '22 Ayar'), (18, '18 Ayar'), (14, '14 Ayar'), (8, '8 Ayar')], default=24, help_text='Milyem hesabı için altın ayarı. 24=1.000, 22=0.916, 18=0.750, 14=0.585, 8=0.333.', verbose_name='Varsayılan Ayar')),
                ('default_invoice_labor_type', models.CharField(choices=[('AMOUNT', 'Sabit Tutar (TL — KDV Dahil)'), ('PERCENT', 'Yüzde (%)')], default='PERCENT', help_text='AMOUNT → labor_value sabit TL (KDV dahil). PERCENT → labor_value toplam üzerinden yüzde (Örn: 5.00 = %5).', max_length=10, verbose_name='İşçilik Tipi')),
                ('default_invoice_labor_value', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='PERCENT modu için yüzde (Örn: 5.0000 = %5). AMOUNT modu için KDV DAHİL TL tutarı.', max_digits=12, verbose_name='İşçilik Değeri')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'E-Fatura Mağaza Ayarları',
                'verbose_name_plural': 'E-Fatura Mağaza Ayarları',
            },
        ),
        migrations.CreateModel(
            name='EInvoiceCreditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ef_credit_decisions', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ef_credit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
