# Generated by Django 6.0.4 on 2026-04-28 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('invoices', '0001_initial'),
        ('process', '0001_initial'),
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='einvoicecreditrequest',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ef_credit_requests', to='stores.stores'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='customers.customers'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='process.process'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='stores.stores'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='suppliers.suppliers'),
        ),
        migrations.AddField(
            model_name='invoiceactivitylog',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceactivitylog',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Müşteri izolasyonu için — her kullanıcı sadece kendi mağazasını görür', null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.stores'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.products'),
        ),
        migrations.AddField(
            model_name='invoicepaymentallocation',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='invoicepaymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_allocations', to='process.payment'),
        ),
        migrations.AddField(
            model_name='invoicesequence',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sequences', to='stores.stores'),
        ),
        migrations.AddField(
            model_name='invoicesynclog',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='invoicesynclog',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.stores'),
        ),
        migrations.AddField(
            model_name='storeeinvoicesettings',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='einvoice_settings', to='stores.stores'),
        ),
        migrations.AddIndex(
            model_name='einvoicecreditrequest',
            index=models.Index(fields=['store', 'status'], name='invoices_ei_store_i_e64387_idx'),
        ),
        migrations.AddIndex(
            model_name='einvoicecreditrequest',
            index=models.Index(fields=['created_at'], name='invoices_ei_created_d5d059_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['store', 'issue_date'], name='Invoices_store_i_e6070f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['store', 'status'], name='Invoices_store_i_78de0f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer'], name='Invoices_custome_c66e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['supplier'], name='Invoices_supplie_7bc826_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_no'], name='Invoices_invoice_cabef9_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('store', 'invoice_no', 'invoice_type'), name='uniq_invoice_no_per_store_type'),
        ),
        migrations.AddIndex(
            model_name='invoiceactivitylog',
            index=models.Index(fields=['invoice', '-created_at'], name='InvoiceActi_invoice_72823b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceactivitylog',
            index=models.Index(fields=['store', 'level', '-created_at'], name='InvoiceActi_store_i_e9f0ff_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice'], name='InvoiceItem_invoice_468c75_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicepaymentallocation',
            index=models.Index(fields=['invoice'], name='InvoicePaym_invoice_0f786b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicepaymentallocation',
            index=models.Index(fields=['payment'], name='InvoicePaym_payment_1679be_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicesequence',
            index=models.Index(fields=['store', 'year', 'seq_type'], name='invoices_in_store_i_788da1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoicesequence',
            unique_together={('store', 'year', 'seq_type')},
        ),
        migrations.AddIndex(
            model_name='invoicesynclog',
            index=models.Index(fields=['invoice', '-created_at'], name='InvoiceSync_invoice_619fee_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicesynclog',
            index=models.Index(fields=['status', 'action'], name='InvoiceSync_status_d5ad53_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicesynclog',
            index=models.Index(fields=['store', '-created_at'], name='InvoiceSync_store_i_292b4e_idx'),
        ),
    ]
