# Generated by Django 6.0.4 on 2026-04-28 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplateCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('category', models.CharField(blank=True, default='', max_length=32)),
                ('default_language', models.CharField(default='tr_TR', max_length=16)),
                ('header_placeholders', models.PositiveIntegerField(default=0)),
                ('body_placeholders', models.PositiveIntegerField(default=0)),
                ('button_placeholders', models.PositiveIntegerField(default=0)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'WA Şablon (Katalog)',
                'verbose_name_plural': 'WA Şablon Kataloğu',
                'db_table': 'WhatsAppTemplateCatalog',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoreWhatsAppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('allow_generic', models.BooleanField(default=True)),
                ('allow_two_fa', models.BooleanField(default=True)),
                ('allow_repair', models.BooleanField(default=True)),
                ('allow_op_sum', models.BooleanField(default=True)),
                ('allowed_templates', models.JSONField(blank=True, default=list)),
                ('daily_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_count', models.PositiveIntegerField(default=0)),
                ('daily_reset', models.DateField(blank=True, null=True)),
                ('monthly_count', models.PositiveIntegerField(default=0)),
                ('monthly_reset', models.DateField(blank=True, null=True)),
                ('credit_balance', models.PositiveIntegerField(blank=True, default=250, null=True)),
                ('low_balance_threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('last_topup_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wa_settings', to='stores.stores')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=32)),
                ('started_by', models.CharField(choices=[('CUSTOMER', 'Müşteri Başlattı'), ('STORE', 'Mağaza Başlattı')], default='CUSTOMER', max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'Açık'), ('CLOSED', 'Kapalı')], default='OPEN', max_length=16)),
                ('subject', models.CharField(blank=True, default='', max_length=160)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_conversations', to='stores.stores')),
            ],
            options={
                'db_table': 'WhatsAppConversation',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'Inbound'), ('OUT', 'Outbound')], max_length=3)),
                ('kind', models.CharField(choices=[('TEXT', 'Text'), ('MEDIA', 'Media'), ('TEMPLATE', 'Template')], default='TEXT', max_length=16)),
                ('wa_message_id', models.CharField(blank=True, default='', max_length=100)),
                ('from_number', models.CharField(blank=True, default='', max_length=32)),
                ('to_number', models.CharField(blank=True, default='', max_length=32)),
                ('text', models.TextField(blank=True, default='')),
                ('media', models.JSONField(blank=True, default=dict)),
                ('template_name', models.CharField(blank=True, default='', max_length=120)),
                ('template_params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(blank=True, default='DELIVERED', max_length=24)),
                ('error', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customers')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_chat_messages', to='stores.stores')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappconversation')),
            ],
            options={
                'db_table': 'WhatsAppChatMessage',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppCreditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_credit_decisions', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_credit_requests', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_credit_requests', to='stores.stores')),
            ],
            options={
                'db_table': 'WhatsAppCreditRequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=32)),
                ('template', models.CharField(max_length=120)),
                ('language', models.CharField(default='tr_TR', max_length=16)),
                ('msg_type', models.CharField(choices=[('GENERIC', 'Genel'), ('2FA', 'İki Aşamalı Doğrulama'), ('REPAIR', 'Tamir İşlem Özeti'), ('OP_SUM', 'Perakende İşlem Özeti')], default='GENERIC', max_length=16)),
                ('header_params', models.JSONField(blank=True, null=True)),
                ('body_params', models.JSONField(blank=True, null=True)),
                ('button_params', models.JSONField(blank=True, null=True)),
                ('response_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('SENT', 'Gönderildi'), ('FAILED', 'Hata'), ('BLOCKED_QUOTA', 'Kota Engeli'), ('BLOCKED_POLICY', 'Politika Engeli')], max_length=20)),
                ('error_code', models.CharField(blank=True, default='', max_length=32)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='whatsapp.whatsappconversation')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customers')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_messages', to='stores.stores')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'WhatsAppMessageLog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='SEND', max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_activities', to='stores.stores')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='whatsapp.whatsappmessagelog')),
            ],
            options={
                'db_table': 'WhatsAppActivity',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreWhatsAppEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(max_length=40, unique=True)),
                ('display_phone_number', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_endpoints', to='stores.stores')),
            ],
            options={
                'verbose_name': 'WA Uç Noktası',
                'verbose_name_plural': 'WA Uç Noktaları',
                'db_table': 'StoreWhatsAppEndpoint',
                'indexes': [models.Index(fields=['store', 'is_active'], name='StoreWhatsA_store_i_68d4c8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='whatsappconversation',
            constraint=models.UniqueConstraint(fields=('store', 'phone_number'), name='uq_conv_store_phone'),
        ),
        migrations.AddIndex(
            model_name='whatsappchatmessage',
            index=models.Index(fields=['store', 'conversation', 'timestamp'], name='WhatsAppCha_store_i_bfbf05_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcreditrequest',
            index=models.Index(fields=['store', 'status'], name='WhatsAppCre_store_i_1a2123_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcreditrequest',
            index=models.Index(fields=['created_at'], name='WhatsAppCre_created_7f9935_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['store', 'created_at'], name='WhatsAppMes_store_i_54edfe_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['store', 'status'], name='WhatsAppMes_store_i_51d121_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['template'], name='WhatsAppMes_templat_48b8eb_idx'),
        ),
    ]
