# Generated by Django 6.0.4 on 2026-04-28 15:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=100)),
                ('material_type', models.CharField(choices=[('GOLD', 'Altın'), ('SILVER', 'Gümüş'), ('DIAMOND', 'Pırlanta'), ('WATCH', 'Saat')], db_index=True, default='GOLD', help_text='Şablonun ait olduğu ürün tipi — form tabları bu değere göre filtrelenir.', max_length=10)),
                ('jewelry_type', models.CharField(blank=True, default='', max_length=100)),
                ('gold_rate', models.CharField(blank=True, default='', max_length=10)),
                ('product_mileage', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('labor_mileage', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('piece_labor', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ring_size', models.CharField(blank=True, default='', max_length=10, verbose_name='Alyans Numarası')),
                ('process_supplier_ledger', models.BooleanField(default=False, verbose_name='Tedarikçi Carisine İşle')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Material-type özel alanları. Pırlanta: mount_metal, mount_karat, mount_gram, sale_currency, sale_price, buy_price_tl, diamond_shape, ... Saat: watch_condition, watch_movement_type, watch_case_material, sale_currency, sale_price, buy_price_tl, ...')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'BarcodeTemplates',
            },
        ),
        migrations.CreateModel(
            name='GoldPurchases',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('count_is_status', models.IntegerField(blank=True, choices=[(0, 'Yapılmadı'), (1, 'Yapıldı'), (2, 'Hatalı')], default=0, null=True)),
                ('is_status', models.BooleanField(blank=True, default=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('is_labeled', models.BooleanField(default=False, verbose_name='Etiket Basıldı')),
            ],
            options={
                'db_table': 'GoldPurchases',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('barcode_prefix', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ProductCategories',
            },
        ),
    ]
