# Generated by Django 6.0.4 on 2026-05-09 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gold_purchases', '0001_initial'),
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barcodetemplate',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_templates', to='stores.stores'),
        ),
        migrations.AddField(
            model_name='barcodetemplate',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.suppliers'),
        ),
        migrations.AddField(
            model_name='goldpurchases',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goldpurchases',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.products'),
        ),
        migrations.AddField(
            model_name='goldpurchases',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.stores'),
        ),
        migrations.AddField(
            model_name='goldpurchases',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.suppliers'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='stores.stores'),
        ),
        migrations.AddIndex(
            model_name='barcodetemplate',
            index=models.Index(fields=['store', 'is_deleted', 'is_active'], name='bt_store_active_idx'),
        ),
        migrations.AddIndex(
            model_name='barcodetemplate',
            index=models.Index(fields=['store', 'material_type', 'is_deleted'], name='bt_store_mat_idx'),
        ),
        migrations.AddIndex(
            model_name='goldpurchases',
            index=models.Index(fields=['store', 'is_deleted'], name='gp_store_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='goldpurchases',
            index=models.Index(fields=['store', '-created_on'], name='gp_store_created_idx'),
        ),
        migrations.AddIndex(
            model_name='goldpurchases',
            index=models.Index(fields=['supplier'], name='goldpurchases_supplier_idx'),
        ),
        migrations.AddIndex(
            model_name='goldpurchases',
            index=models.Index(fields=['-created_on'], name='gp_created_on_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['store', 'is_deleted', 'is_active'], name='pc_store_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('store', 'barcode_prefix')},
        ),
    ]
