# Generated by Django 6.0.4 on 2026-04-28 15:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0002_initial'),
        ('customers', '0002_initial'),
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('process_no', models.CharField(max_length=15, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.stores')),
            ],
            options={
                'db_table': 'ProcessGroup',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('process_no', models.CharField(blank=True, max_length=15, null=True)),
                ('process_type', models.CharField(choices=[('RETAIL', 'Perakende'), ('WHOLESALE', 'Toptan'), ('FAST_PROCESS', 'Hızlı İşlem')], default='RETAIL', max_length=150)),
                ('transaction_type', models.CharField(choices=[('STOCK_IN', 'Stok Girişi'), ('ORDER_IN', 'Sipariş'), ('PURCHASE', 'Alış'), ('SALE', 'Satış'), ('RETURN', 'İade'), ('PAYMENT', 'Ödeme')], default='SALE', max_length=150)),
                ('payment_currency', models.CharField(blank=True, help_text='FX kasası için döviz kodu (USD, EUR vb.). Normal kasalarda boş kalır.', max_length=10, null=True, verbose_name='Ödeme Para Birimi')),
                ('piece', models.IntegerField(default=0)),
                ('gram', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Brüt Ticari Kâr (Cebine Giren)')),
                ('net_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Net Kâr (KDV/Vergi Düşülmüş)')),
                ('cost_amount_tl', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True, verbose_name='Maliyet (TL)')),
                ('cost_amount_hs', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=12, null=True, verbose_name='Maliyet (Has)')),
                ('process_mileage', models.CharField(default=0, max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('price_hs', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=10, null=True)),
                ('hs_rate_sale_tl', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('hs_rate_buy_tl', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('karat', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('labor_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Özel matrah kapsamında brüt işçilik toplamı (TL).', max_digits=12, null=True)),
                ('waiting_stock', models.BooleanField(default=False)),
                ('invoice_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='Fatura No')),
                ('invoice_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fatura Linki')),
                ('is_status', models.CharField(choices=[('PENDING', 'Beklemede'), ('OPEN_BINDING', 'Açıktan Bağlama'), ('COMPLETED', 'Tamamlandı'), ('IN_PROGRESS', 'Tamamlanmadı'), ('CANCELED', 'İptal Edildi'), ('WAITING_STOCK', 'Bekleyen Stok')], default='IN_PROGRESS', max_length=15)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bank_account', models.ForeignKey(blank=True, help_text='Kasa/ödeme sepet kalemleri için. Dolu ise bu satır ürün değil kasa çıkışıdır.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_items', to='banking.bankaccount', verbose_name='Banka Hesabı (Kasa)')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customers')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.products')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.stores')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.suppliers')),
                ('process_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_items', to='process.processgroup', verbose_name='İşlem Grubu')),
            ],
            options={
                'db_table': 'Process',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('process_no', models.CharField(blank=True, max_length=15, null=True)),
                ('payment_type', models.CharField(choices=[('CASH', 'Nakit'), ('CREDIT_CARD', 'Kredi Kartı'), ('TRANSFER', 'Havale / EFT'), ('COMMISSION', 'Komisyon'), ('ADJUSTMENT', 'Bakiye Düzeltme / Açılış')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_output', models.BooleanField(default=False)),
                ('installment', models.IntegerField(blank=True, default=1, null=True, verbose_name='Taksit Sayısı')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='POS Referans/Ref No')),
                ('commission_rate_applied', models.DecimalField(blank=True, decimal_places=2, help_text='Ödeme anında POS komisyon oranı.', max_digits=5, null=True, verbose_name='Uygulanan Komisyon Oranı (%)')),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, help_text='amount * commission_rate / 100', max_digits=15, null=True, verbose_name='Komisyon Tutarı (TL)')),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, help_text='amount - commission_amount. Mutabakat bu tutara göre yapılır.', max_digits=15, null=True, verbose_name='Net Tutar (Bankaya Gelen)')),
                ('maturity_date', models.DateField(blank=True, help_text='Tutarın banka hesabına geçeceği tahmini tarih.', null=True, verbose_name='Vade Tarihi')),
                ('reconciliation_status', models.CharField(choices=[('NOT_REQUIRED', 'Mutabakat Gerekmez'), ('PENDING', 'Bekliyor'), ('MATCHED', 'Eşleşti'), ('PARTIAL', 'Kısmi Eşleşme'), ('DISCREPANCY', 'Tutar Uyuşmazlığı'), ('MANUAL', 'Manuel Teyit Edildi')], default='NOT_REQUIRED', help_text='NOT_REQUIRED: Nakit/komisyon — mutabakat gerekmez. PENDING: Banka teyidi bekleniyor. MATCHED: Banka hareketi ile eşleşti. PARTIAL: Kısmi tutar eşleşmesi. DISCREPANCY: Tutar uyuşmazlığı (banka komisyonu aşımı). MANUAL: Personel tarafından manuel teyit edildi.', max_length=15, verbose_name='Mutabakat Durumu')),
                ('reconciliation_diff', models.DecimalField(blank=True, decimal_places=2, help_text='Banka tutarı - İç kayıt tutarı. Pozitif = bankaya fazla gelmiş, Negatif = eksik gelmiş (komisyon). Debugging ve raporlama için saklanır.', max_digits=15, null=True, verbose_name='Mutabakat Farkı (TL)')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='Mutabakat Zamanı')),
                ('is_cancelled', models.BooleanField(default=False, help_text='True ise bu ödeme kaydı iptal edilmiştir. Bakiye hesaplamaları ve raporlarda dikkate alınmaz.', verbose_name='İptal Edildi')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='İptal işleminin gerçekleştiği tarih ve saat.', null=True, verbose_name='İptal Zamanı')),
                ('currency_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Kasanın para birimi TRY değilse, döviz cinsinden gerçek tutar. Örn: amount=13887 TL, exchange_rate=46.29 → currency_amount=300 USD. TRY kasaları için NULL kalır.', max_digits=15, null=True, verbose_name='Döviz Tutarı')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, help_text='İşlem anındaki TRY/Döviz kuru. Örn: 1 USD = 46.29 TL → exchange_rate=46.29. TRY kasaları için NULL kalır.', max_digits=12, null=True, verbose_name='Döviz Kuru')),
                ('is_approved', models.BooleanField(default=True, help_text='False ise bu ödeme yönetici onayı beklemektedir. Bakiye hesaplamalarına dahil edilmez. Onaylandığında True olur ve bakiyeye yansır.', verbose_name='Onaylandı')),
                ('notes', models.TextField(blank=True, help_text='İşlem hakkında serbest metin açıklama. reference alanı POS referans kodu için ayrılmıştır; uzun açıklamalar bu alana yazılır.', null=True, verbose_name='Açıklama / Not')),
                ('bank_account', models.ForeignKey(blank=True, help_text='CREDIT_CARD ise POS terminali, TRANSFER ise banka hesabı seçilir. CASH ve COMMISSION için boş kalır.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='banking.bankaccount', verbose_name='Banka/POS Hesabı')),
                ('matched_bank_transaction', models.ForeignKey(blank=True, help_text='ReconciliationService tarafından doldurulur. Payment (iç kayıt) ile BankTransaction (dış kayıt) arasındaki bağlantı.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_payments', to='banking.banktransaction', verbose_name='Eşleşen Banka Hareketi')),
                ('performed_by', models.ForeignKey(blank=True, help_text='Ödemeyi veya transferi gerçekleştiren kullanıcı. reconciled_by ile karıştırılmamalıdır (o mutabakat içindir).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_payments', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan Personel')),
                ('reconciled_by', models.ForeignKey(blank=True, help_text='Otomatik eşleşmelerde NULL kalır, manuel eşleşmelerde personel kaydedilir.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_payments', to=settings.AUTH_USER_MODEL, verbose_name='Mutabakatı Yapan')),
                ('process_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='process.processgroup', verbose_name='İşlem Grubu')),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
        migrations.AddIndex(
            model_name='processgroup',
            index=models.Index(fields=['store'], name='processgroup_store_idx'),
        ),
        migrations.AddIndex(
            model_name='processgroup',
            index=models.Index(fields=['-created_at'], name='processgroup_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['process_no'], name='process_no_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['process_group'], name='process_process_group_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['store', 'is_deleted', 'is_status'], name='proc_store_del_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['store', 'date'], name='process_store_date_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['store', 'transaction_type'], name='process_store_txtype_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['customer'], name='process_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['employee'], name='process_employee_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['is_deleted'], name='process_is_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['-date'], name='process_date_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['process_no'], name='payment_process_no_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['process_group'], name='payment_process_group_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['date'], name='payment_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['bank_account', 'reconciliation_status'], name='payment_bank_recon_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reconciliation_status', 'date'], name='payment_recon_date_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_cancelled'], name='payment_cancelled_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_approved'], name='payment_approved_idx'),
        ),
    ]
