# Generated by Django 6.0.4 on 2026-05-09 16:01

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCountItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_counted', models.BooleanField(default=False)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'InventoryCountItem',
            },
        ),
        migrations.CreateModel(
            name='InventoryCountSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('scope_type', models.CharField(choices=[('ALL', 'Tüm Mağaza'), ('CATEGORY', 'Kategori'), ('MATERIAL', 'Materyal Tipi'), ('BRAND', 'Marka'), ('JEWELRY_TYPE', 'Mücevher Tipi')], db_index=True, default='ALL', help_text='Oturumun hangi alt küme için başlatıldığını belirtir. ALL: Tüm mağaza (varsayılan, geriye uyum). CATEGORY/MATERIAL/BRAND/JEWELRY_TYPE: scope_filter alanı bu tip için hangi değerlerin kapsama dahil olduğunu içerir.', max_length=16, verbose_name='Sayım Kapsam Tipi')),
                ('scope_filter', models.JSONField(blank=True, default=dict, help_text='Kapsam tipine göre uygulanacak filtre değerleri (ID listeleri veya string listeleri). ALL için {} — boş. JSON şemasını backend yorumlar.', verbose_name='Kapsam Filtre Parametreleri')),
                ('scope_label', models.CharField(blank=True, default='', help_text="Raporlarda ve UI'da gösterilecek okunur metin. Örn: '14 Ayar Yüzükler', 'Rolex Koleksiyonu'. ALL için boş bırakılır.", max_length=255, verbose_name='Kapsam Etiketi')),
            ],
            options={
                'db_table': 'InventoryCountSession',
            },
        ),
    ]
