# Generated by Django 6.0.4 on 2026-04-28 15:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsProfiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dil')),
                ('api_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Api Url')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kullanıcı Adı')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Şifre')),
                ('sms_header', models.CharField(blank=True, max_length=50, null=True, verbose_name='SMS Başlığı')),
                ('sms_provider', models.CharField(blank=True, max_length=50, null=True, verbose_name='SMS Sağlayıcısı')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'SmsProfiles',
                'ordering': ['name'],
            },
        ),
    ]
