# Generated by Django 6.0.4 on 2026-04-28 15:27

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PavoAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Varsayılan', max_length=120)),
                ('provider', models.CharField(choices=[('PAVO', 'Pavo')], default='PAVO', max_length=32)),
                ('base_url', models.CharField(blank=True, max_length=300, null=True)),
                ('api_key', models.CharField(blank=True, max_length=200, null=True)),
                ('api_secret', models.CharField(blank=True, max_length=200, null=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=200, null=True)),
                ('pairing_source_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('pairing_target_serial_no', models.CharField(blank=True, max_length=120, null=True)),
                ('pairing_application_name', models.CharField(blank=True, max_length=120, null=True)),
                ('pairing_source_reference', models.CharField(blank=True, max_length=120, null=True)),
                ('test_mode', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pavo_accounts', to='stores.company')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pavo_accounts', to='stores.stores')),
            ],
            options={
                'db_table': 'PavoAccounts',
            },
        ),
        migrations.CreateModel(
            name='PavoPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, max_length=100)),
                ('pavo_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('payment_url', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='TRY', max_length=6)),
                ('status', models.CharField(default='CREATED', max_length=32)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('raw_request', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='pavo.pavoaccount')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pavo_payments', to='invoices.invoice')),
            ],
            options={
                'db_table': 'PavoPayments',
            },
        ),
        migrations.CreateModel(
            name='PavoTerminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Terminal', max_length=120)),
                ('ip', models.CharField(max_length=64)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('secure', models.BooleanField(default=True)),
                ('serial_number', models.CharField(max_length=120)),
                ('fingerprint', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_paired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pavo_terminals', to='stores.stores')),
            ],
            options={
                'db_table': 'PavoTerminals',
            },
        ),
        migrations.CreateModel(
            name='PavoLocalSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_payload', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='SENT', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='TRY', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pavo_local_sales', to='invoices.invoice')),
                ('terminal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_sales', to='pavo.pavoterminal')),
            ],
            options={
                'db_table': 'PavoLocalSales',
            },
        ),
        migrations.CreateModel(
            name='PavoWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headers', models.JSONField(default=dict)),
                ('body', models.JSONField(default=dict)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('result', models.CharField(default='RECEIVED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoice')),
                ('pavo_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pavo.pavopayment')),
            ],
            options={
                'db_table': 'PavoWebhookEvents',
            },
        ),
        migrations.AddIndex(
            model_name='pavoaccount',
            index=models.Index(fields=['company', 'store', 'is_active'], name='PavoAccount_company_e77a53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pavoaccount',
            unique_together={('company', 'store', 'title')},
        ),
        migrations.AddIndex(
            model_name='pavopayment',
            index=models.Index(fields=['external_id', 'status'], name='PavoPayment_externa_57483a_idx'),
        ),
        migrations.AddIndex(
            model_name='pavoterminal',
            index=models.Index(fields=['store', 'is_active'], name='PavoTermina_store_i_b55576_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pavoterminal',
            unique_together={('store', 'serial_number')},
        ),
        migrations.AddIndex(
            model_name='pavolocalsale',
            index=models.Index(fields=['status', 'created_at'], name='PavoLocalSa_status_421d96_idx'),
        ),
        migrations.AddIndex(
            model_name='pavowebhookevent',
            index=models.Index(fields=['created_at', 'processed'], name='PavoWebhook_created_5dc163_idx'),
        ),
    ]
