# Generated by Django 6.0.4 on 2026-04-28 15:27

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('process_no', models.CharField(blank=True, max_length=15, null=True)),
                ('movement_type', models.CharField(choices=[('entry', 'Giriş'), ('exit', 'Çıkış'), ('transfer', 'Transfer'), ('update', 'Manuel Güncelleme')], max_length=20)),
                ('quantity_pieces', models.IntegerField(default=0)),
                ('quantity_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('stock_before_pieces', models.IntegerField(blank=True, default=0, null=True)),
                ('stock_after_pieces', models.IntegerField(blank=True, default=0, null=True)),
                ('stock_before_weight', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('stock_after_weight', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'InventoryMovement',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Inventories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_pieces', models.IntegerField(default=0)),
                ('stock_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('incoming_stock_pieces', models.IntegerField(default=0)),
                ('incoming_stock_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('use_custom_pricing', models.BooleanField(default=False, verbose_name='Özel Fiyat Kullan')),
                ('weighted_buy_price_hs', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('custom_buy_price_hs', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=10, null=True, verbose_name='Özel Alış Has')),
                ('custom_sale_price_hs', models.DecimalField(blank=True, decimal_places=4, default=Decimal('0.0000'), max_digits=10, null=True, verbose_name='Özel Satış Has')),
                ('custom_fixed_labor', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True, verbose_name='Özel Sabit İşçilik')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Inventories',
                'ordering': ['-created_on'],
            },
        ),
    ]
