# Generated by Django 6.0.4 on 2026-05-09 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventories', '0001_initial'),
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventories',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_inventories', to='products.products'),
        ),
        migrations.AddField(
            model_name='inventories',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.stores'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='products.products'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.stores'),
        ),
        migrations.AddIndex(
            model_name='inventories',
            index=models.Index(fields=['store', 'product'], name='inventories_store_product_idx'),
        ),
        migrations.AddIndex(
            model_name='inventories',
            index=models.Index(fields=['store'], name='inventories_store_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventories',
            unique_together={('store', 'product')},
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['store', 'product'], name='invmovement_store_product_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['process_no'], name='invmovement_process_no_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['store', '-created_on'], name='invmovement_store_created_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['movement_type'], name='invmovement_type_idx'),
        ),
    ]
