# Generated by Django 6.0.4 on 2026-04-28 15:27

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255, verbose_name='Firma Ünvanı')),
                ('person_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Yetkili Adı')),
                ('person_surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Yetkili Soyadı')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_payer_type', models.CharField(choices=[('INDIVIDUAL', 'Şahıs / Bireysel'), ('CORPORATE', 'Tüzel Kişi / Şirket')], default='CORPORATE', max_length=20, verbose_name='Mükellefiyet Türü')),
                ('tax_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='VKN / TCKN')),
                ('is_einvoice_user', models.BooleanField(default=False, verbose_name='E-Fatura Mükellefi')),
                ('post_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Posta Kodu')),
                ('company_address', models.TextField(blank=True, null=True, verbose_name='Açık Adres (Cadde, Sokak, Kapı No)')),
                ('account_type', models.CharField(blank=True, choices=[('SUPPLIER', 'Tedarikçi'), ('CANTACI', 'Çantacı')], help_text='NULL veya SUPPLIER = Tedarikçi, CANTACI = Çantacı', max_length=20, null=True, verbose_name='Hesap Türü')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city', verbose_name='İl')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.district', verbose_name='İlçe')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.stores')),
                ('tax_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='locations.taxoffice', verbose_name='Vergi Dairesi')),
            ],
            options={
                'db_table': 'Suppliers',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('ENTRY', 'Giriş (Borç)'), ('EXIT', 'Çıkış (Alacak)')], max_length=5)),
                ('cantaci_tx_type', models.CharField(blank=True, choices=[('HURDA_VERILDI', 'Hurda Verildi'), ('URUN_ALINDI', 'Ürün Alındı'), ('ODEME', 'Ödeme'), ('TAHSILAT', 'Tahsilat')], help_text='Çantacı hesaplarında işlem alt tipini belirtir', max_length=20, null=True, verbose_name='Çantacı İşlem Tipi')),
                ('quantity_piece', models.IntegerField(default=0)),
                ('quantity_gram', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount_value', models.DecimalField(decimal_places=3, max_digits=14)),
                ('currency', models.CharField(max_length=50)),
                ('exchange_rate_tl', models.DecimalField(blank=True, decimal_places=6, help_text='İşlem anında 1 birim currency karşılığı kaç TL olduğunu saklar (örn. 1 USD = 45.50 TL için 45.500000). Fiat para birimli ürünlerde iptal/reversal sırasında korunur. HS/HG (metal) ledger kayıtlarında NULL bırakılabilir.', max_digits=18, null=True, verbose_name='İşlem Anındaki Kur (TL Karşılığı)')),
                ('process_no', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.products')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='suppliers.suppliers')),
            ],
            options={
                'db_table': 'SupplierLedgers',
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['supplier', 'currency', 'transaction_type', 'is_active'], name='SupplierLed_supplie_a266a7_idx'), models.Index(fields=['process_no'], name='SupplierLed_process_fc9237_idx'), models.Index(fields=['created_on'], name='SupplierLed_created_b6d2d0_idx')],
            },
        ),
    ]
