# Generated by Django 6.0.4 on 2026-05-09 16:01

import apps.settings.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chambers', '0001_initial'),
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('de', 'Almanca (Deutsch)'), ('en', 'İngilizce (English)'), ('tr', 'Türkçe')], default='tr', help_text='Bu mağazanın tüm kullanıcıları için uygulama dilini zorlar.', max_length=5, verbose_name='Mağaza Dili')),
                ('base_spot_currency', models.CharField(choices=[('USD', 'ABD Doları (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'Sterlin (GBP)'), ('CAD', 'Kanada Doları (CAD)'), ('AUD', 'Avustralya Doları (AUD)'), ('JPY', 'Japon Yeni (JPY)'), ('CHF', 'İsviçre Frangı (CHF)')], default='EUR', help_text='Dinamik spot fiyat ekranında kullanılacak para birimi. Mevcut işlem kayıtlarını etkilemez.', max_length=3, verbose_name='Spot Fiyat Taban Para Birimi')),
                ('base_spot_unit', models.CharField(choices=[('OZ', 'Troy Ons (oz)'), ('GRAM', 'Gram (g)'), ('KILO', 'Kilogram (kg)'), ('TOLA', 'Tola')], default='OZ', help_text='Canlı spot fiyat okurken kullanılacak ağırlık birimi.', max_length=5, verbose_name='Spot Fiyat Taban Birimi')),
                ('price_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('-50.00')), django.core.validators.MaxValueValidator(Decimal('50.00'))], verbose_name='Fiyat Marjı (%)')),
                ('use_average_labor', models.BooleanField(default=False, verbose_name='Ortalama İşçilik Kullan')),
                ('use_manual_has_calculation', models.BooleanField(default=False, verbose_name='Manuel Has Hesabı Kullan')),
                ('use_manual_currency_rate', models.BooleanField(default=False, help_text='Açıkken döviz ürünleri (USDTRY, EURTRY vb.) için API kurları yerine manuel girilen TL kurları kullanılır. Kapatınca API kuru otomatik devreye girer.', verbose_name='Manuel Kur Ayarı (Döviz)')),
                ('manual_currency_rates', models.JSONField(blank=True, default=dict, help_text='Döviz ürünleri için per-store TL kur override\'ları. Format: {"<product_uuid>": {"buy_tl": "45.20", "sell_tl": "46.50"}}', verbose_name="Manuel Kur Override'ları")),
                ('is_safe_approval_required', models.BooleanField(default=False, help_text="Açıldığında kasaya giriş-çıkış yapan her ödeme kaydı 'Beklemede' durumunda oluşturulur. Bakiyeye yansıması için yönetici onayı gerekir.", verbose_name='Onaylı Kasa: Yönetici Onayı Gereksin')),
                ('enforce_customer_always', models.BooleanField(default=False, help_text='Açıldığında Hızlı İşlem ve Perakende ekranlarında her ödemede (tutar bağımsız) müşteri seçimi zorunlu hale gelir.', verbose_name='Zorunluluk: Her İşlemde Müşteri Seçimi')),
                ('require_customer_phone', models.BooleanField(default=True, help_text='Yeni müşteri kaydında ve güncellemede telefon zorunlu olsun.', verbose_name='Müşteri Kayıt: Telefon Zorunlu')),
                ('require_customer_tckn', models.BooleanField(default=False, help_text='Yeni müşteri kaydında ve güncellemede kimlik numarası zorunlu olsun.', verbose_name='Müşteri Kayıt: T.C. / Vergi Kimlik Zorunlu')),
                ('notify_email_2fa', models.BooleanField(default=True, verbose_name='E-posta: İki Faktörlü Doğrulama')),
                ('notify_email_staff_login', models.BooleanField(default=True, verbose_name='E-posta: Personel Giriş Bildirimi')),
                ('notify_email_ops', models.BooleanField(default=True, verbose_name='E-posta: Genel İşlem Özetleri')),
                ('notify_email_workshops', models.BooleanField(default=True, verbose_name='Atolye Mailleri')),
                ('notify_email_repair_updates', models.BooleanField(default=True, verbose_name='E-posta: Tamir Kaydı ve Durum Güncellemeleri')),
                ('notify_email_reports', models.BooleanField(default=True, verbose_name='E-posta: Rapor Bildirimleri')),
                ('debt_currency_mode', models.CharField(choices=[('HS', 'Has (gram) — borç gram cinsinden sabit'), ('EUR', 'EUR — borç Euro cinsinden sabit')], default='HS', help_text='HS: Borç gram cinsinden sabit. EUR: Borç Euro cinsinden sabit (kur dalgalandıkça gram karşılığı değişir).', max_length=4, verbose_name='Cari Borç Birim Modu')),
                ('allow_overpayment_default', models.BooleanField(default=False, help_text='Tahsilat ekranında "Fazla Tahsilatı Kabul Et" toggle\'ı varsayılan olarak açık gelsin. Kullanıcı yine kapatabilir.', verbose_name='Tahsilat: Fazla Tahsilatı Varsayılan Kabul Et')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_pricing_chamber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores_using_pricing', to='chambers.chambers', verbose_name='Referans Fiyat Derneği')),
                ('default_24k_product', models.ForeignKey(blank=True, help_text='Banka havalesi → toplu faturaya dönüştürme sırasında otomatik kalem olarak eklenecek 24 ayar külçe altın ürünü.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_as_default_gold', to='products.products', verbose_name='Varsayılan 24 Ayar Altın Ürünü')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='stores.stores')),
            ],
            options={
                'verbose_name': 'Mağaza Ayarı',
                'verbose_name_plural': 'Mağaza Ayarları',
                'db_table': 'StoreConfiguration',
            },
        ),
        migrations.CreateModel(
            name='StoreLabelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_size', models.CharField(choices=[('small', 'Küçük Etiket'), ('large', 'Büyük Etiket')], default='small', max_length=10, verbose_name='Aktif Etiket Boyutu')),
                ('small_design', models.JSONField(default=apps.settings.models.default_small_config, verbose_name='Küçük Etiket Tasarımı')),
                ('large_design', models.JSONField(default=apps.settings.models.default_large_config, verbose_name='Büyük Etiket Tasarımı')),
                ('diamond_small_design', models.JSONField(blank=True, default=apps.settings.models.default_diamond_small_config, null=True, verbose_name='Pırlanta Küçük Etiket Tasarımı')),
                ('diamond_large_design', models.JSONField(blank=True, default=apps.settings.models.default_diamond_large_config, null=True, verbose_name='Pırlanta Büyük Etiket Tasarımı')),
                ('watch_small_design', models.JSONField(blank=True, default=apps.settings.models.default_watch_small_config, null=True, verbose_name='Saat Küçük Etiket Tasarımı')),
                ('watch_large_design', models.JSONField(blank=True, default=apps.settings.models.default_watch_large_config, null=True, verbose_name='Saat Büyük Etiket Tasarımı')),
                ('label_bottom_left_type', models.CharField(choices=[('MILYEM', 'Milyem'), ('MALIYET', 'Maliyet (Has)')], default='MILYEM', max_length=10, verbose_name='Sol Alt Köşe Verisi')),
                ('label_layout_mode', models.CharField(choices=[('STANDARD', 'Standart (Alt Alta)'), ('REFLECTED', 'Yansımalı (Kelebek)'), ('SIDE_BY_SIDE', 'Yan Yana (Çiftli)')], default='STANDARD', max_length=15, verbose_name='Etiket Düzeni')),
                ('barcode_lines_x', models.IntegerField(default=200, verbose_name='Barkod Çizgileri X')),
                ('barcode_lines_y', models.IntegerField(default=127, verbose_name='Barkod Çizgileri Y')),
                ('barcode_lines_height', models.IntegerField(default=35, verbose_name='Barkod Çizgileri Yükseklik')),
                ('barcode_lines_visible', models.BooleanField(default=True, verbose_name='Barkod Çizgileri Görünür')),
                ('rfid_mode', models.BooleanField(default=True, verbose_name='RFID Yazıcı Modu')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='label_settings', to='stores.stores')),
            ],
            options={
                'db_table': 'StoreLabelSettings',
            },
        ),
    ]
