# Generated by Django 6.0.5 on 2026-05-11 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeconfiguration',
            name='active_pricing_chamber',
        ),
        migrations.RemoveField(
            model_name='storeconfiguration',
            name='manual_currency_rates',
        ),
        migrations.RemoveField(
            model_name='storeconfiguration',
            name='price_margin_percent',
        ),
        migrations.RemoveField(
            model_name='storeconfiguration',
            name='require_customer_tckn',
        ),
        migrations.RemoveField(
            model_name='storeconfiguration',
            name='use_average_labor',
        ),
        migrations.RemoveField(
            model_name='storeconfiguration',
            name='use_manual_currency_rate',
        ),
        migrations.RemoveField(
            model_name='storeconfiguration',
            name='use_manual_has_calculation',
        ),
    ]
