# Generated by Django 6.0.5 on 2026-05-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_storeconfiguration_active_pricing_chamber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeconfiguration',
            name='primary_currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('TRY', 'Türk Lirası (₺)'), ('USD', 'ABD Doları ($)'), ('GBP', 'Sterlin (£)'), ('CHF', 'İsviçre Frangı (CHF)'), ('CAD', 'Kanada Doları (C$)'), ('AUD', 'Avustralya Doları (A$)'), ('JPY', 'Japon Yeni (¥)')], default='EUR', help_text='Tüm satış/alış/kasa işlemlerinin temel para birimi. Otomatik nakit kasası bu birimde oluşturulur, fiyat etiketleri ve raporlar bu birim sembolüyle gösterilir.', max_length=3, verbose_name='Mağaza Birincil Para Birimi'),
        ),
    ]
