# Generated by Django 6.0.4 on 2026-04-28 15:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Şehir Adı')),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('plate_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Plaka Kodu')),
            ],
            options={
                'verbose_name': 'Şehir',
                'verbose_name_plural': 'Şehirler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='İlçe Adı')),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='locations.city', verbose_name='Şehir')),
            ],
            options={
                'verbose_name': 'İlçe',
                'verbose_name_plural': 'İlçeler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxOffice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Vergi Dairesi Kodu')),
                ('name', models.CharField(max_length=255, verbose_name='Vergi Dairesi/Malmüdürlüğü Adı')),
                ('office_type', models.CharField(choices=[('VD', 'Vergi Dairesi'), ('MAL', 'Malmüdürlüğü')], default='VD', max_length=3, verbose_name='Tip')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_offices', to='locations.city', verbose_name='Şehir')),
            ],
            options={
                'verbose_name': 'Vergi Dairesi',
                'verbose_name_plural': 'Vergi Daireleri',
                'ordering': ['code'],
            },
        ),
    ]
