# Generated by Django 6.0.4 on 2026-04-28 15:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasakBlacklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='Ad Soyad')),
                ('identification_number', models.CharField(db_index=True, max_length=50, verbose_name='TCKN/VKN/Pasaport')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Sebep')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'MasakBlacklist',
            },
        ),
        migrations.CreateModel(
            name='MasakOfficialList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_info', models.TextField(db_index=True, verbose_name='Kimlik Bilgileri')),
                ('full_name', models.CharField(db_index=True, max_length=500, verbose_name='Ad Soyad / Unvan')),
                ('source_type', models.CharField(choices=[('BMGK', 'BMGK Kararları (5. Madde)'), ('FOREIGN', 'Yabancı Ülke Talepleri (6. Madde)'), ('INTERNAL', 'İç Dondurma Kararları (7. Madde/FETÖ/PKK vb.)')], default='INTERNAL', max_length=20)),
                ('organization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bağlantılı Örgüt')),
                ('birth_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Doğum Tarihi')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Uyruk')),
                ('gazette_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Resmi Gazete Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MASAK Resmi Liste',
                'db_table': 'MasakOfficialList',
            },
        ),
        migrations.CreateModel(
            name='MasakQueryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('queried_tckn', models.CharField(blank=True, max_length=50, null=True)),
                ('queried_name', models.CharField(blank=True, max_length=255, null=True)),
                ('result_status', models.CharField(choices=[('CLEAN', 'Temiz'), ('SUSPICIOUS', 'Şüpheli')], default='CLEAN', max_length=20)),
                ('result_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'MasakQueryLog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerMasakDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_type', models.CharField(choices=[('BIREYSEL', 'Bireysel'), ('KURUMSAL', 'Kurumsal')], default='BIREYSEL', max_length=10, verbose_name='Müşteri Tipi')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adı')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Soyadı')),
                ('identity_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Kimlik/Pasaport No')),
                ('nationality', models.CharField(blank=True, max_length=80, null=True, verbose_name='Uyruğu')),
                ('document_type', models.CharField(blank=True, choices=[('TC', 'T.C. Kimlik Kartı'), ('PASAPORT', 'Pasaport'), ('EHLIYET', 'Sürücü Belgesi'), ('DIGER', 'Diğer')], default='TC', max_length=20, null=True, verbose_name='Belge Türü')),
                ('document_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Belge Numarası')),
                ('birth_place', models.CharField(blank=True, max_length=120, null=True, verbose_name='Doğum Yeri')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefon')),
                ('occupation', models.CharField(blank=True, max_length=150, null=True, verbose_name='İş/Meslek')),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Anne Adı')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Baba Adı')),
                ('id_front_image', models.ImageField(blank=True, null=True, upload_to='masak/id_front/%Y/%m/', verbose_name='Kimlik Ön Yüz')),
                ('id_back_image', models.ImageField(blank=True, null=True, upload_to='masak/id_back/%Y/%m/', verbose_name='Kimlik Arka Yüz')),
                ('company_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Şirket Unvanı')),
                ('tax_office', models.CharField(blank=True, max_length=150, null=True, verbose_name='Vergi Dairesi')),
                ('tax_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Vergi Numarası (VKN)')),
                ('mersis_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='MERSİS Numarası')),
                ('trade_registry_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ticaret Sicil Numarası')),
                ('activity_field', models.CharField(blank=True, max_length=250, null=True, verbose_name='Faaliyet Konusu')),
                ('company_address', models.TextField(blank=True, null=True, verbose_name='Şirket Merkez Adresi')),
                ('rep_first_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Yetkili Adı')),
                ('rep_last_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Yetkili Soyadı')),
                ('rep_identity_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Yetkili TCKN')),
                ('rep_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Yetkili Ünvanı')),
                ('beneficial_owner_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Gerçek Faydalanıcı Adı')),
                ('beneficial_owner_identity', models.CharField(blank=True, max_length=30, null=True, verbose_name='Gerçek Faydalanıcı TCKN')),
                ('beneficial_owner_share', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ortaklık Payı')),
                ('consent_kvkk', models.BooleanField(default=False, verbose_name='KVKK Onayı')),
                ('consent_acik_riza', models.BooleanField(default=False, verbose_name='Açık Rıza Onayı')),
                ('consent_iys_sms', models.BooleanField(default=False, verbose_name='İYS SMS')),
                ('consent_iys_email', models.BooleanField(default=False, verbose_name='İYS E-posta')),
                ('consent_iys_call', models.BooleanField(default=False, verbose_name='İYS Arama')),
                ('consent_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Onay Zamanı')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='masak_declaration', to='customers.customers', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'MASAK Beyan Formu',
                'verbose_name_plural': 'MASAK Beyan Formları',
                'db_table': 'CustomerMasakDeclaration',
                'ordering': ('-submitted_at',),
            },
        ),
    ]
