# Generated by Django 6.0.4 on 2026-04-28 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('masak', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customermasakdeclaration',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masak_declarations', to='stores.stores', verbose_name='Mağaza'),
        ),
        migrations.AddField(
            model_name='masakblacklist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='masakblacklist',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masak_blacklist', to='stores.stores'),
        ),
        migrations.AddIndex(
            model_name='masakofficiallist',
            index=models.Index(fields=['identity_info'], name='MasakOffici_identit_76b1bd_idx'),
        ),
        migrations.AddIndex(
            model_name='masakofficiallist',
            index=models.Index(fields=['full_name'], name='MasakOffici_full_na_81b47a_idx'),
        ),
        migrations.AddField(
            model_name='masakquerylog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customers'),
        ),
        migrations.AddField(
            model_name='masakquerylog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='masakquerylog',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masak_logs', to='stores.stores'),
        ),
        migrations.AlterUniqueTogether(
            name='masakblacklist',
            unique_together={('store', 'identification_number')},
        ),
    ]
