# Generated by Django 6.0.4 on 2026-04-28 15:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('content_snapshot', models.TextField(blank=True, null=True, verbose_name='Sözleşme Metni (Snapshot)')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='contract_signatures/%Y/%m/', verbose_name='İmza Görseli')),
                ('document_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='Dosya Hash (SHA256)')),
                ('process_type', models.CharField(choices=[('SALES', 'Satış'), ('DEMO', 'Demo')], default='SALES', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Onay Bekliyor'), ('SIGNED', 'İmzalandı'), ('EXPIRED', 'Süresi Doldu'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=10)),
                ('signer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='İmzalayan Telefon')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='SMS Kodu')),
                ('sms_uuid', models.CharField(blank=True, max_length=100, null=True, verbose_name='Netgsm JobID')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='İmzalama Tarihi')),
                ('signer_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='İmzalayan IP')),
                ('signer_user_agent', models.TextField(blank=True, null=True, verbose_name='Tarayıcı/Cihaz Bilgisi')),
                ('signed_content_snapshot', models.TextField(blank=True, null=True, verbose_name='İmzalanan Metin Kopyası')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ContractProcesses',
            },
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sözleşme Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Sözleşme İçeriği/Açıklama')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Contracts',
                'ordering': ['-created_at'],
            },
        ),
    ]
