# Generated by Django 6.0.4 on 2026-04-28 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('packages', '0001_initial'),
        ('proposals', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractprocess',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.company'),
        ),
        migrations.AddField(
            model_name='contractprocess',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.packages'),
        ),
        migrations.AddField(
            model_name='contractprocess',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_processes', to='proposals.proposals', verbose_name='İlgili Teklif'),
        ),
        migrations.AddField(
            model_name='contractprocess',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.stores'),
        ),
        migrations.AddField(
            model_name='contractprocess',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contracts', verbose_name='İlgili Sözleşme'),
        ),
    ]
