# Generated by Django 6.0.4 on 2026-04-28 15:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('symbol', models.CharField(blank=True, max_length=3, null=True)),
                ('digit_group_separator', models.TextField(blank=True, null=True)),
                ('decimal_character', models.TextField(blank=True, null=True)),
                ('round', models.CharField(blank=True, max_length=5, null=True)),
                ('splice', models.CharField(blank=True, max_length=1, null=True)),
                ('after_comma', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField()),
                ('modified_on', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currencies_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Currencies',
                'ordering': ['name'],
            },
        ),
    ]
