# Generated by Django 6.0.4 on 2026-04-28 15:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('leads', '0001_initial'),
        ('packages', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposal_no', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('sent', 'Gönderildi'), ('accepted', 'Onaylandı'), ('rejected', 'Reddedildi'), ('revised', 'Revize Edildi')], default='draft', max_length=20)),
                ('currency', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR')], default='USD', max_length=3)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, default=Decimal('20.00'), max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('private_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='stores.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_proposals', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='leads.lead')),
            ],
            options={
                'db_table': 'Proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalLogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50, verbose_name='İşlem Tipi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='İşlem Tarihi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='proposals.proposals')),
            ],
            options={
                'db_table': 'ProposalLogs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mağaza/Şube Adı')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('maintenance_included', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.device')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_items', to='packages.saasmodule', verbose_name='İlgili Modül')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.packages')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proposals.proposals')),
            ],
            options={
                'db_table': 'ProposalItems',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='proposals',
            index=models.Index(fields=['proposal_no'], name='Proposals_proposa_cbe9a1_idx'),
        ),
        migrations.AddIndex(
            model_name='proposals',
            index=models.Index(fields=['status'], name='Proposals_status_35bffb_idx'),
        ),
        migrations.AddIndex(
            model_name='proposals',
            index=models.Index(fields=['lead'], name='Proposals_lead_id_222284_idx'),
        ),
        migrations.AddIndex(
            model_name='proposals',
            index=models.Index(fields=['company'], name='Proposals_company_a22413_idx'),
        ),
    ]
