# Generated by Django 6.0.4 on 2026-04-28 15:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100, verbose_name='Modül Adı')),
                ('title', models.CharField(max_length=255, verbose_name='Video Başlığı')),
                ('youtube_id', models.CharField(help_text="YouTube video ID'si (Örn: dQw4w9WgXcQ)", max_length=50, verbose_name='YouTube Video ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Eğitim Videosu',
                'verbose_name_plural': 'Eğitim Videoları',
                'db_table': 'TrainingVideos',
                'ordering': ['module_name', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PersonelSupport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_no', models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True, verbose_name='Talep No')),
                ('category', models.CharField(choices=[('error', 'Hata'), ('developer', 'Geliştirme'), ('support', 'Teknik Destek')], default='error', max_length=20)),
                ('title', models.CharField(max_length=255, verbose_name='Konu')),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('ASSIGNED', 'Personel Atandı'), ('IN_PROGRESS', 'İşlemde'), ('STOPPED', 'Durduruldu'), ('WAITING', 'Müşteri Yanıtı Bekleniyor'), ('RESOLVED', 'Çözüldü'), ('CANCELLED', 'İptal Edildi')], default='PENDING', max_length=20, verbose_name='Durum')),
                ('priority', models.CharField(choices=[('LOW', 'Düşük'), ('MEDIUM', 'Orta'), ('HIGH', 'Yüksek'), ('CRITICAL', 'Kritik')], default='MEDIUM', max_length=20, verbose_name='Öncelik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('created_at_start', models.DateTimeField(blank=True, null=True)),
                ('created_at_end', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Kapanış Tarihi')),
                ('is_deleted', models.BooleanField(default=False)),
                ('closing_reason', models.CharField(blank=True, choices=[('RESOLVED', 'Çözüldü (Başarılı)'), ('SOFTWARE_UPDATE', 'Yazılım Güncellemesi Yapıldı'), ('USER_ERROR', 'Kullanıcı Hatası / Eğitim Verildi'), ('UNRESOLVABLE', 'Teknik Olarak İmkansız / Reddedildi'), ('DUPLICATE', 'Mükerrer Talep'), ('OTHER', 'Diğer')], max_length=50, null=True, verbose_name='Kapanış Nedeni')),
                ('closing_description', models.TextField(blank=True, null=True, verbose_name='Kapanış Açıklaması')),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Personel')),
                ('personel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personel_request', to=settings.AUTH_USER_MODEL, verbose_name='Talep Oluşturan')),
            ],
            options={
                'verbose_name': 'Müşteri Talebi',
                'verbose_name_plural': 'Müşteri Talepleri',
                'db_table': 'PersonelSupports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='supports/replies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_new_message', models.BooleanField(default=True)),
                ('is_internal_log', models.BooleanField(default=False, verbose_name='Sistem Logu mu?')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='supports.personelsupport')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'verbose_name': 'Talep Mesajı',
                'verbose_name_plural': 'Talep Mesajları',
                'db_table': 'RequestMessages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportWorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='supports.personelsupport')),
            ],
            options={
                'db_table': 'SupportWorkSessions',
                'ordering': ['start_time'],
            },
        ),
    ]
