# Generated by Django 6.0.4 on 2026-05-09 16:01

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ticari Unvan / Ad Soyad')),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='İl')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='İlçe')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Posta Kodu')),
                ('country', models.CharField(default='Türkiye', max_length=50)),
                ('tax_office', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vergi Dairesi')),
                ('tax_office_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Vergi Dairesi Kodu')),
                ('tax_number', models.CharField(blank=True, max_length=45, null=True, unique=True, verbose_name='VKN / TCKN')),
                ('mersis_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='MERSİS No')),
                ('trade_registry_no', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ticaret Sicil No')),
                ('iban', models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN')),
                ('e_invoice_type', models.CharField(choices=[('TEMEL', 'Temel Fatura'), ('TICARI', 'Ticari Fatura')], default='TEMEL', max_length=10, verbose_name='E-Fatura Senaryo Tipi')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='Companies/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Companies',
                'indexes': [models.Index(fields=['is_active'], name='Companies_is_acti_4452ad_idx'), models.Index(fields=['tax_number'], name='Companies_tax_num_a78c28_idx'), models.Index(fields=['tax_office_code'], name='Companies_tax_off_378412_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_id', models.CharField(blank=True, editable=False, max_length=25, null=True, unique=True, verbose_name='Mağaza Kimlik No')),
                ('masak_public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='İl')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='İlçe')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Posta Kodu')),
                ('country', models.CharField(default='Türkiye', max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mağaza Adı / Ekran Adı')),
                ('barcode_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Barkod Adı')),
                ('avatar', models.ImageField(blank=True, default='default/store.png', null=True, upload_to='Stores/')),
                ('description', models.TextField(blank=True, null=True)),
                ('subscription_start', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DEMO', 'Demo'), ('PENDING_PAYMENT', 'Ödeme Bekleniyor'), ('ACTIVE', 'Aktif'), ('EXPIRED', 'Süresi Doldu'), ('SUSPENDED', 'Askıya Alındı')], db_index=True, default='ACTIVE', help_text="Mağazanın yaşam döngüsündeki güncel durumu. is_active boolean'ı ile birlikte okunur.", max_length=20, verbose_name='Mağaza Statüsü')),
                ('demo_expires_at', models.DateTimeField(blank=True, help_text='Yalnızca status=DEMO için doludur. Süre dolduğunda otomatik EXPIRED olur.', null=True, verbose_name='Demo Bitiş Zamanı')),
                ('demo_converted_at', models.DateTimeField(blank=True, help_text='Demo mağazanın ücretli pakete geçtiği an damgalanır.', null=True, verbose_name='Demo→Aktif Dönüşüm Zamanı')),
                ('onboarding_source', models.CharField(choices=[('corporate', 'Kurumsal (Teklif)'), ('fast_track', 'Hızlı Kayıt (Demo)'), ('manual', 'Manuel (Admin)')], default='manual', help_text='Bu mağaza hangi akışla sisteme dahil oldu?', max_length=20, verbose_name='Kayıt Kaynağı')),
                ('branch_type', models.CharField(choices=[('MAIN', 'Ana Merkez'), ('BRANCH', 'Şube'), ('MOBILE', 'Mobil / Plasiyer')], db_index=True, default='MAIN', help_text='Şubenin sistemsel rolü. MAIN: ana merkez, BRANCH: fiziksel şube, MOBILE: plasiyer/çantacı.', max_length=10, verbose_name='Şube Tipi')),
                ('branch_code', models.CharField(blank=True, help_text='İnsan-okunabilir benzersiz kod (örn: MRK, ŞB1, PLY1). Transfer fişlerinde gösterilir.', max_length=20, null=True, unique=True, verbose_name='Şube Kısa Kodu')),
                ('is_branch_active', models.BooleanField(db_index=True, default=True, help_text='Geçici kapatma için kullanılır. Kapalı şubeye transfer başlatılamaz. is_active ile birlikte okunur.', verbose_name='Şube Operasyonel mi?')),
                ('allows_inbound_transfer', models.BooleanField(default=True, help_text='Bu şubeye başka şubelerden transfer gönderilebilir mi? Bazı plasiyer şubeler sadece çıkış-yönlü çalışabilir.', verbose_name='Gelen Transferi Kabul Eder')),
                ('transfer_auto_approve', models.BooleanField(default=False, help_text='Tek kişi çalışan küçük şubelerde gelen transferi otomatik kabul eder. Varsayılan kapalıdır; insan onayı zorunludur.', verbose_name='Transferi Otomatik Onayla')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='stores.company')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.packages')),
                ('parent_store', models.ForeignKey(blank=True, help_text='Bu kayıt bir alt şube ise bağlı olduğu ana merkez. MAIN tipindeki şubelerde NULL kalır.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_branches', to='stores.stores', verbose_name='Ana Şube (Merkez)')),
            ],
            options={
                'db_table': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='StorePriceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_buy_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('has_sale_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_cache', to='stores.stores')),
            ],
            options={
                'db_table': 'StorePriceCache',
            },
        ),
        migrations.CreateModel(
            name='StoreModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activated_at', models.DateTimeField(auto_now_add=True, verbose_name='Aktivasyon Tarihi')),
                ('note', models.CharField(blank=True, help_text='Ek modül atamasına dair açıklama.', max_length=200, verbose_name='Not')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_stores', to='packages.saasmodule', verbose_name='Modül')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_modules', to='stores.stores', verbose_name='Mağaza')),
            ],
            options={
                'verbose_name': 'Mağaza Modülü',
                'verbose_name_plural': 'Mağaza Modülleri',
                'db_table': 'StoreModules',
            },
        ),
        migrations.AddIndex(
            model_name='stores',
            index=models.Index(fields=['company', 'is_active'], name='Stores_company_e8930e_idx'),
        ),
        migrations.AddIndex(
            model_name='stores',
            index=models.Index(fields=['status'], name='Stores_status_35cc6c_idx'),
        ),
        migrations.AddIndex(
            model_name='stores',
            index=models.Index(fields=['status', 'demo_expires_at'], name='Stores_status_e0f699_idx'),
        ),
        migrations.AddIndex(
            model_name='stores',
            index=models.Index(fields=['parent_store', 'branch_type'], name='stores_parent_type_idx'),
        ),
        migrations.AddIndex(
            model_name='stores',
            index=models.Index(fields=['branch_type', 'is_branch_active'], name='stores_btype_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='storemodule',
            unique_together={('store', 'module')},
        ),
    ]
