# Generated by Django 6.0.4 on 2026-05-09 16:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('buy_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Alış')),
                ('sale_price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Satış')),
                ('modified_on', models.DateTimeField(blank=True, null=True)),
                ('market_time', models.DateTimeField(blank=True, max_length=20, null=True, verbose_name='Piyasa Tarihi')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('currency_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_one', to='currencies.currencies')),
                ('currency_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_two', to='currencies.currencies')),
            ],
            options={
                'db_table': 'Rates',
            },
        ),
    ]
