# Generated by Django 6.0.4 on 2026-05-09 16:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProfiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dil')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Kullanıcı Adı')),
                ('password', models.CharField(blank=True, max_length=150, null=True, verbose_name='Şifre')),
                ('server', models.CharField(blank=True, max_length=150, null=True, verbose_name='E-posta Sunucusu')),
                ('port', models.CharField(blank=True, max_length=150, null=True, verbose_name='Port')),
                ('sender', models.CharField(blank=True, max_length=150, null=True, verbose_name='Gönderen')),
                ('ssl', models.BooleanField(blank=True, default=False, null=True, verbose_name='SSL')),
                ('tls', models.BooleanField(blank=True, default=False, null=True, verbose_name='TSL')),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'EmailProfiles',
                'ordering': ['name'],
            },
        ),
    ]
