# Generated by Django 6.0.4 on 2026-05-09 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
        ('customers', '0001_initial'),
        ('process', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='stores.stores'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='IBAN eşleşmesinden otomatik doldurulur. Mutabakat motorunun Payment ile karşılaştırma yapabilmesi için her iki tarafta da aynı BankAccount referansı bulunmalıdır.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='banking.bankaccount', verbose_name='Banka Hesabı'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='customers.customers', verbose_name='Eşleşen Cari'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='stores.stores', verbose_name='Mağaza'),
        ),
        migrations.AddField(
            model_name='cashboxledger',
            name='cashbox',
            field=models.ForeignKey(help_text='CashboxLedger satırlarının yazılabileceği BankAccount. account_type=CASH/BANK/POS olabilir; tipik olarak CASH kasaları için kullanılır ama tüm tipler desteklenir.', on_delete=django.db.models.deletion.PROTECT, related_name='cashbox_ledger_entries', to='banking.bankaccount', verbose_name='Kasa'),
        ),
        migrations.AddField(
            model_name='cashboxledger',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashbox_ledger_entries', to=settings.AUTH_USER_MODEL, verbose_name='Yazan Kullanıcı'),
        ),
        migrations.AddField(
            model_name='cashboxledger',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='movement_type=REVERSAL ise iptal edilen orijinal satır. Append-Only ihlali olmadan iptal akışını sağlar.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='banking.cashboxledger', verbose_name='Orijinal Satır (REVERSAL için)'),
        ),
        migrations.AddField(
            model_name='cashboxledger',
            name='related_payment',
            field=models.ForeignKey(blank=True, help_text='Tahsilat veya ödeme akışından gelen Payment kaydı. Kasa-Cari mutabakatının iki ucu arasındaki bağ.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashbox_entries', to='process.payment', verbose_name='İlişkili Ödeme'),
        ),
        migrations.AddField(
            model_name='cashboxledger',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashbox_ledger_entries', to='stores.stores', verbose_name='Mağaza'),
        ),
        migrations.AddField(
            model_name='dailycashclose',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_closes', to='banking.bankaccount', verbose_name='Kasa'),
        ),
        migrations.AddField(
            model_name='dailycashclose',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_closes', to=settings.AUTH_USER_MODEL, verbose_name='Kapatan Kullanici'),
        ),
        migrations.AddField(
            model_name='dailycashclose',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_cash_closes', to='stores.stores'),
        ),
        migrations.AddField(
            model_name='esurectenantcredential',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esurec_credential', to='stores.stores', verbose_name='Mağaza'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expense_categories', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='stores.stores', verbose_name='Mağaza'),
        ),
        migrations.AddField(
            model_name='incomeexpenseledger',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_expense_entries', to=settings.AUTH_USER_MODEL, verbose_name='Yazan Kullanıcı'),
        ),
        migrations.AddField(
            model_name='incomeexpenseledger',
            name='expense_category',
            field=models.ForeignKey(blank=True, help_text='OTHER_EXPENSE / OTHER_INCOME tipi manuel gider kalemleri için operasyonel kategori (Yemek, Kargo, Atölye vb.). Diğer entry tiplerinde NULL kalır.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='banking.expensecategory', verbose_name='Gider Kategorisi'),
        ),
        migrations.AddField(
            model_name='incomeexpenseledger',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='banking.incomeexpenseledger', verbose_name='Orijinal Satır (REVERSAL için)'),
        ),
        migrations.AddField(
            model_name='incomeexpenseledger',
            name='related_customer_ledger',
            field=models.ForeignKey(blank=True, help_text='DISCOUNT/FX_GAIN/FX_LOSS/WRITEOFF tipinde bir CustomerLedger kaydının onaylanması sonucunda yazıldıysa, kaynak satır.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_expense_entries', to='customers.customerledger', verbose_name='İlişkili Cari Hareket'),
        ),
        migrations.AddField(
            model_name='incomeexpenseledger',
            name='related_payment',
            field=models.ForeignKey(blank=True, help_text="POS komisyon gideri gibi Payment'a bağlı kalemler için.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_expense_entries', to='process.payment', verbose_name='İlişkili Ödeme'),
        ),
        migrations.AddField(
            model_name='incomeexpenseledger',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_expense_entries', to='stores.stores', verbose_name='Mağaza'),
        ),
        migrations.AddField(
            model_name='cashboxledger',
            name='related_expense',
            field=models.ForeignKey(blank=True, help_text='Kasa girişi/çıkışı bir muhasebe gelir/gider kalemi ile ilişkili ise (örn. iskonto zararının nakit yansıması).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashbox_entries', to='banking.incomeexpenseledger', verbose_name='İlişkili Gelir/Gider Kaydı'),
        ),
        migrations.AddField(
            model_name='poscommissionrate',
            name='bank_account',
            field=models.ForeignKey(limit_choices_to={'account_type': 'POS'}, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rates', to='banking.bankaccount', verbose_name='POS Hesabı'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['store', 'account_type', 'is_active'], name='kp_ba_store_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['store', 'doc_date'], name='kp_bank_store_date_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['store', 'match_status'], name='kp_bank_store_match_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['api_transaction_id'], name='kp_bank_api_id_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['other_vkn_tckn'], name='kp_bank_vkn_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['bank_account'], name='kp_bank_account_idx'),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('api_transaction_id__isnull', False)), fields=('store', 'api_transaction_id'), name='uniq_kp_bank_txn_per_store'),
        ),
        migrations.AlterUniqueTogether(
            name='dailycashclose',
            unique_together={('store', 'bank_account', 'date')},
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['store', 'is_active', 'display_order'], name='kp_expense_cat_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='kp_expense_cat_store_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='incomeexpenseledger',
            index=models.Index(fields=['store', 'entry_type', 'created_on'], name='kp_iel_store_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='incomeexpenseledger',
            index=models.Index(fields=['related_customer_ledger'], name='kp_iel_cl_idx'),
        ),
        migrations.AddIndex(
            model_name='incomeexpenseledger',
            index=models.Index(fields=['expense_category', 'created_on'], name='kp_iel_cat_date_idx'),
        ),
        migrations.AddIndex(
            model_name='cashboxledger',
            index=models.Index(fields=['cashbox', 'created_on'], name='kp_cb_cashbox_date_idx'),
        ),
        migrations.AddIndex(
            model_name='cashboxledger',
            index=models.Index(fields=['store', 'movement_type', 'created_on'], name='kp_cb_store_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='cashboxledger',
            index=models.Index(fields=['process_no'], name='kp_cb_process_no_idx'),
        ),
        migrations.AddIndex(
            model_name='poscommissionrate',
            index=models.Index(fields=['bank_account', 'is_active'], name='kp_pcr_ba_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='poscommissionrate',
            unique_together={('bank_account', 'card_type', 'installment_count')},
        ),
    ]
