# Generated by Django 6.0.4 on 2026-04-28 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
        ('customers', '0001_initial'),
        ('invoices', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='stores.stores'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='IBAN eşleşmesinden otomatik doldurulur. Mutabakat motorunun Payment ile karşılaştırma yapabilmesi için her iki tarafta da aynı BankAccount referansı bulunmalıdır.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='banking.bankaccount', verbose_name='Banka Hesabı'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='customers.customers', verbose_name='Eşleşen Cari'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='invoices.invoice', verbose_name='Bağlı Fatura'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='stores.stores', verbose_name='Mağaza'),
        ),
        migrations.AddField(
            model_name='dailycashclose',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_closes', to='banking.bankaccount', verbose_name='Kasa'),
        ),
        migrations.AddField(
            model_name='dailycashclose',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_closes', to=settings.AUTH_USER_MODEL, verbose_name='Kapatan Kullanici'),
        ),
        migrations.AddField(
            model_name='dailycashclose',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_cash_closes', to='stores.stores'),
        ),
        migrations.AddField(
            model_name='esurectenantcredential',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esurec_credential', to='stores.stores', verbose_name='Mağaza'),
        ),
        migrations.AddField(
            model_name='poscommissionrate',
            name='bank_account',
            field=models.ForeignKey(limit_choices_to={'account_type': 'POS'}, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rates', to='banking.bankaccount', verbose_name='POS Hesabı'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['store', 'account_type', 'is_active'], name='kp_ba_store_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['store', 'doc_date'], name='kp_bank_store_date_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['store', 'match_status'], name='kp_bank_store_match_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['api_transaction_id'], name='kp_bank_api_id_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['other_vkn_tckn'], name='kp_bank_vkn_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['bank_account'], name='kp_bank_account_idx'),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('api_transaction_id__isnull', False)), fields=('store', 'api_transaction_id'), name='uniq_kp_bank_txn_per_store'),
        ),
        migrations.AlterUniqueTogether(
            name='dailycashclose',
            unique_together={('store', 'bank_account', 'date')},
        ),
        migrations.AddIndex(
            model_name='poscommissionrate',
            index=models.Index(fields=['bank_account', 'is_active'], name='kp_pcr_ba_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='poscommissionrate',
            unique_together={('bank_account', 'card_type', 'installment_count')},
        ),
    ]
