# Generated by Django 6.0.4 on 2026-05-09 16:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('is_system_only', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Permission',
                'ordering': ['group', 'order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('SYSTEM', 'Sistem (Konasoft)'), ('STORE', 'Mağaza (Kuyumcu)'), ('CHAMBER', 'Dernek / Oda')], db_index=True, default='STORE', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('store', models.ForeignKey(blank=True, help_text='NULL ise global rol; dolu ise yalnızca bu mağazada geçerli izole rol.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_roles', to='stores.stores', verbose_name='Mağaza')),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='RoleDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.roles')),
            ],
            options={
                'db_table': 'RoleDetail',
            },
        ),
        migrations.AddIndex(
            model_name='roles',
            index=models.Index(fields=['category', 'store', 'is_active'], name='Role_categor_e34953_idx'),
        ),
        migrations.AddConstraint(
            model_name='roledetail',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='uniq_role_permission_package'),
        ),
    ]
